# Generated by Django 6.0.3 on 2026-04-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForRent',
            fields=[
                ('property_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('no_of_rooms', models.IntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='branches.branch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='users.client')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='users.staff')),
            ],
            options={
                'verbose_name_plural': 'Properties for Rent',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(max_length=150)),
                ('advert_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='properties.propertyforrent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'newspaper_name', 'advert_date'), name='unique_property_advert')],
            },
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.propertyforrent')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='users.staff')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'inspection_date'), name='unique_property_inspection')],
            },
        ),
        migrations.CreateModel(
            name='PropertyViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='properties.propertyforrent')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='users.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'renter', 'view_date'), name='unique_property_viewing')],
            },
        ),
    ]
