# Generated by Django 6.0.3 on 2026-04-03 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0003_client_remove_propertyowner_user_remove_renter_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyforrent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='users.client'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='users.client'),
        ),
    ]
