# Generated by Django 6.0.3 on 2026-04-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0003_remove_client_birthdate_remove_client_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforrent',
            name='date_withdrawn',
            field=models.DateField(blank=True, help_text='Date the property was removed from the market.', null=True),
        ),
        migrations.AlterField(
            model_name='propertyforrent',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'Owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='users.client'),
        ),
        migrations.AlterField(
            model_name='propertyforrent',
            name='property_no',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyforrent',
            name='property_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('House', 'House')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyforrent',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Withdrawn', 'Withdrawn')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='renter',
            field=models.ForeignKey(limit_choices_to={'role': 'Renter'}, on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='users.client'),
        ),
    ]
