# Generated by Django 6.0.3 on 2026-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyforrent_date_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforrent',
            name='description',
            field=models.TextField(default='A Property', help_text='Full description of the property features and area.'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='title',
            field=models.CharField(default='A Property for Rent', help_text='e.g. Stunning 2-Bed Flat in City Centre', max_length=200),
        ),
    ]
