# Generated by Django 6.0.3 on 2026-05-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_rename_manager_branch_manager_no'),
        ('leases', '0003_rename_property_leaseagreement_property_no_and_more'),
        ('properties', '0003_propertyforrent_description_propertyforrent_title'),
        ('users', '0009_alter_client_date_registered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyForRent',
            new_name='Property',
        ),
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='unique_property_advert',
        ),
        migrations.RemoveConstraint(
            model_name='propertyinspection',
            name='unique_property_inspection',
        ),
        migrations.RemoveConstraint(
            model_name='propertyviewing',
            name='unique_property_viewing',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='branch',
            new_name='branch_no',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='owner_no',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='staff',
            new_name='staff_no',
        ),
        
        # --- NEW RENAME BLOCKS (Replaces AddField and RemoveField) ---
        migrations.RenameField(
            model_name='advertisement',
            old_name='property',
            new_name='property_no',
        ),
        migrations.RenameField(
            model_name='propertyinspection',
            old_name='property',
            new_name='property_no',
        ),
        migrations.RenameField(
            model_name='propertyinspection',
            old_name='staff',
            new_name='staff_no',
        ),
        migrations.RenameField(
            model_name='propertyviewing',
            old_name='property',
            new_name='property_no',
        ),
        migrations.RenameField(
            model_name='propertyviewing',
            old_name='renter',
            new_name='renter_no',
        ),
        # -------------------------------------------------------------
        
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.UniqueConstraint(fields=('property_no', 'newspaper_name', 'advert_date'), name='unique_property_advert'),
        ),
        migrations.AddConstraint(
            model_name='propertyinspection',
            constraint=models.UniqueConstraint(fields=('property_no', 'inspection_date'), name='unique_property_inspection'),
        ),
        migrations.AddConstraint(
            model_name='propertyviewing',
            constraint=models.UniqueConstraint(fields=('property_no', 'renter_no', 'view_date'), name='unique_property_viewing'),
        ),
    ]