# Generated by Django 6.0.3 on 2026-05-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_propertyforrent_property_and_more'),
        ('users', '0009_alter_client_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='property_no',
            field=models.ForeignKey(db_column='property_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyinspection',
            name='property_no',
            field=models.ForeignKey(db_column='property_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyinspection',
            name='staff_no',
            field=models.ForeignKey(db_column='staff_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='property_no',
            field=models.ForeignKey(db_column='property_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='renter_no',
            field=models.ForeignKey(db_column='renter_no', limit_choices_to={'role': 'Renter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='users.client'),
        ),
    ]
