# Generated by Django 6.0.4 on 2026-05-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_advertisement_property_no_and_more'),
    ]

    operations = [
    migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION auto_set_date_withdrawn()
RETURNS TRIGGER AS $$
BEGIN
    -- When status changes TO 'Withdrawn', record today's date
    IF NEW.status = 'Withdrawn' AND (OLD.status IS DISTINCT FROM 'Withdrawn') THEN
        NEW.date_withdrawn := CURRENT_DATE;
    -- When status changes FROM 'Withdrawn' back to something else, clear the date
    ELSIF OLD.status = 'Withdrawn' AND NEW.status != 'Withdrawn' THEN
        NEW.date_withdrawn := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trigger_auto_date_withdrawn
BEFORE UPDATE ON properties_property
FOR EACH ROW EXECUTE FUNCTION auto_set_date_withdrawn();

"""
        )
    ]
