# Generated by Django 6.0.4 on 2026-05-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20260506_0845'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Drop the existing function first
DROP FUNCTION IF EXISTS get_owner_property_count(VARCHAR);

-- 2. Create the new updated function
CREATE OR REPLACE FUNCTION get_owner_property_count(p_owner_id VARCHAR)
RETURNS INTEGER AS $$
DECLARE
    v_count INTEGER;
BEGIN
    -- Directly count properties for the specific owner_id
    SELECT COUNT(*) INTO v_count
    FROM property
    WHERE owner_id = p_owner_id;
    
    RETURN v_count;
END;
$$ LANGUAGE plpgsql;"""
        )

    ]
