# Generated by Django 6.0.3 on 2026-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20260506_0920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
        migrations.AlterModelTable(
            name='propertyinspection',
            table='property_inspection',
        ),
        migrations.AlterModelTable(
            name='propertyviewing',
            table='property_viewing',
        ),
    ]
