# Generated by Django 6.0.4 on 2026-05-08 09:11

# pyrefly: ignore [missing-import]
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20260508_1556'),
        ('users', '0010_alter_client_table_alter_nextofkin_table_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE PROCEDURE update_owner_info(
                p_client_no    VARCHAR,
                p_first_name   VARCHAR,
                p_last_name    VARCHAR,
                p_address      VARCHAR,
                p_telephone    VARCHAR,
                p_email        VARCHAR
            )
            LANGUAGE plpgsql AS $$
            DECLARE
                v_role VARCHAR;
            BEGIN
                -- Verify this client is an Owner
                SELECT role INTO v_role
                FROM client
                WHERE client_no = p_client_no;

                IF v_role IS NULL THEN
                    RAISE EXCEPTION 'Client % not found.', p_client_no;
                END IF;

                IF v_role != 'Owner' THEN
                    RAISE EXCEPTION 'Client % is not an Owner. Cannot use this procedure.', p_client_no;
                END IF;

                -- Check email uniqueness (mirrors your model's unique=True on email)
                IF EXISTS (
                    SELECT 1 FROM client
                    WHERE email = p_email AND client_no != p_client_no
                ) THEN
                    RAISE EXCEPTION 'Email % is already used by another client.', p_email;
                END IF;

                UPDATE client
                SET first_name    = p_first_name,
                    last_name     = p_last_name,
                    address       = p_address,
                    telephone_no  = p_telephone,
                    email         = p_email
                WHERE client_no = p_client_no;

                RAISE NOTICE 'Owner % information updated successfully.', p_client_no;
            END;
            $$;
            """,
            reverse_sql="""
            DROP PROCEDURE IF EXISTS update_owner_info(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
            """
        ),
    ]
