# Generated by Django 6.0.3 on 2026-05-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20260510_1526'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION log_property_changes()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    RAISE NOTICE '[INSERT] Property: %, Branch: %, Staff: %, Title: "%", Status: %, By: %, At: %',
                        NEW.property_no, NEW.branch_no_id, NEW.staff_no_id,
                        NEW.title, NEW.status,
                        current_user, now();
                    RETURN NEW;
                ELSIF TG_OP = 'UPDATE' THEN
                    IF NEW.staff_no_id IS NULL THEN
                        RAISE EXCEPTION 'Property updates must be performed by an assigned staff member.';
                    END IF;
                    RAISE NOTICE '[UPDATE] Property: %, Branch: %, Staff: %, Title: "% → %", Status: % → %, By: %, At: %',
                        NEW.property_no, NEW.branch_no_id, NEW.staff_no_id,
                        OLD.title, NEW.title,
                        OLD.status, NEW.status,
                        current_user, now();
                    RETURN NEW;
                ELSIF TG_OP = 'DELETE' THEN
                    RAISE NOTICE '[DELETE] Property: %, Branch: %, Staff: %, Title: "%", Status: %, By: %, At: %',
                        OLD.property_no, OLD.branch_no_id, OLD.staff_no_id,
                        OLD.title, OLD.status,
                        current_user, now();
                    RETURN OLD;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql=""
        ),
    ]
