# Generated by Django 6.0.3 on 2026-05-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_allow_owner_property_updates'),
        ('users', '0017_remove_nextofkin_full_name_client_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyviewing',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_column='decided_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_viewings', to='users.staff'),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20),
        ),
    ]
