# Generated by Django 6.0.3 on 2026-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_propertyviewing_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinspection',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
