# Generated by Django 6.0.3 on 2026-05-11 15:15

import apps.properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_propertyinspection_status'),
        ('users', '0017_remove_nextofkin_full_name_client_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='advertisement',
            name='unique_property_advert',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='assigned_by',
            field=models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_advertisements', to='users.staff'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(default=apps.properties.models.default_advertisement_end_date),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='message',
            field=models.TextField(default='Legacy advertisement (please update)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('Popup', 'Popup'), ('Banner', 'Banner'), ('Section', 'Section')], default='Popup', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(default=apps.properties.models.default_advertisement_start_date),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Untitled Advertisement', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='property_no',
            field=models.ForeignKey(blank=True, db_column='property_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='properties.property'),
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='advert_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='newspaper_name',
        ),
    ]
