# Generated by Django 6.0.3 on 2026-05-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_fix_property_trigger_strictness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Available', 'Available'), ('Rented', 'Rented'), ('Withdrawn', 'Withdrawn')], default='Pending Approval', max_length=50),
        ),
    ]
