# Generated by Django 6.0.3 on 2026-05-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Rejected', 'Rejected'), ('Available', 'Available'), ('Rented', 'Rented'), ('Withdrawn', 'Withdrawn')], default='Pending Approval', max_length=50),
        ),
    ]
