from django.contrib import admin
from .models import Client, Staff  # Import your models here

# This tells Django to display the Client table
@admin.register(Client)
class ClientAdmin(admin.ModelAdmin):
    # This controls the columns you see in the list
    list_display = ('client_no', 'first_name', 'last_name', 'email', 'role')
    
    # This adds a search bar to find users quickly
    search_fields = ('client_no', 'email', 'last_name')

@admin.register(Staff)
class StaffAdmin(admin.ModelAdmin):
    # Change 'role' to 'position' (or whatever you named it in models.py)
    list_display = ('staff_no', 'first_name', 'last_name', 'position') 
    search_fields = ('staff_no', 'last_name')

# Register your models here.
'''
# Generated by Django

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # This tells Django to run this trigger AFTER your previous migration
        ('users', '0005_alter_client_client_no'), 
    ]

    operations = [
        migrations.RunSQL(
            # SQL to run when applying the migration (UP)
            sql="""
            -- Create the sequence generator function
            CREATE OR REPLACE FUNCTION generate_client_no()
            RETURNS VARCHAR AS $$
            DECLARE
                today_str VARCHAR(8);
                last_client_no VARCHAR(12);
                new_seq INT;
            BEGIN
                today_str := to_char(CURRENT_DATE, 'YYYYMMDD');

                SELECT client_no INTO last_client_no
                FROM users_client 
                WHERE client_no LIKE today_str || '%'
                ORDER BY client_no DESC
                LIMIT 1;

                IF last_client_no IS NOT NULL THEN
                    new_seq := CAST(RIGHT(last_client_no, 4) AS INT) + 1;
                ELSE
                    new_seq := 1;
                END IF;

                RETURN today_str || LPAD(new_seq::TEXT, 4, '0');
            END;
            $$ LANGUAGE plpgsql;

            --  Create the trigger function
            CREATE OR REPLACE FUNCTION trigger_set_client_no()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.client_no IS NULL OR NEW.client_no = '' THEN
                    NEW.client_no := generate_client_no();
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Attach the trigger to the table

            CREATE TRIGGER tgr_assign_client_no
            BEFORE INSERT ON users_client
            FOR EACH ROW
            EXECUTE FUNCTION trigger_set_client_no();
            """,
            
            # SQL to run if you ever rollback (undo) this migration (DOWN)
            reverse_sql="""
            DROP TRIGGER IF EXISTS tgr_assign_client_no ON users_client;
            DROP FUNCTION IF EXISTS trigger_set_client_no();
            DROP FUNCTION IF EXISTS generate_client_no();
            """
        )
    ]
'''