# pyrefly: ignore [missing-import]
from rest_framework import generics, serializers, permissions
from django.utils import timezone
# apps/properties/views.py
from .models import Advertisement, Property, PropertyInspection, PropertyViewing
# pyrefly: ignore [missing-import]
from apps.users.models import Client

# ✅ add this import (we created this file already)
from .permissions import ReadOnlyOrAuthenticated

# --- SERIALIZERS ---

class PropertyForRentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Property
        fields = "__all__"
        # property_no is generated by the model. 
        # owner_no and staff_no are handled by perform_create logic.
        read_only_fields = ["property_no", "owner_no", "staff_no"]


class PropertyViewingSerializer(serializers.ModelSerializer):
    class Meta:
        model = PropertyViewing
        fields = "__all__"
        read_only_fields = ["decided_by", "decided_at"]

    def to_representation(self, instance):# pyrefly: ignore 
        representation = super().to_representation(instance)
        # Nested data for frontend display
        from .views import PropertyForRentSerializer
        # pyrefly: ignore [missing-import]
        from apps.users.serializers import ClientSerializer
        
        if instance.property_no:
            representation['property_no'] = PropertyForRentSerializer(instance.property_no).data
        if instance.renter_no:
            representation['renter_no'] = ClientSerializer(instance.renter_no).data
            
        return representation


class PropertyInspectionSerializer(serializers.ModelSerializer):
    class Meta:
        model = PropertyInspection
        fields = "__all__"


class AdvertisementSerializer(serializers.ModelSerializer):
    class Meta:
        model = Advertisement
        fields = "__all__"
        read_only_fields = ["assigned_by"]

    def to_representation(self, instance):
        representation = super().to_representation(instance)
        # Nested data for frontend display
        from .views import PropertyForRentSerializer
        if instance.property_no:
            representation['property_no'] = PropertyForRentSerializer(instance.property_no).data
            
        return representation


# --- HELPERS ---

def get_client_profile_or_error(user):
    try:
        return Client.objects.get(user_no=user)
    except Client.DoesNotExist:
        raise serializers.ValidationError(
            {
                "detail": "Your user account is not linked to a Client profile. "
                        "Create a Client record for this user in the Admin panel."
            }
        )


def is_staff_user(user):
    return bool(user and user.is_authenticated and (user.is_superuser or user.is_staff or hasattr(user, "staff_profile")))


# --- VIEWS ---

class PropertyForRentListCreateView(generics.ListCreateAPIView):
    """
    Public READ (GET), authenticated WRITE (POST).
    Supports ?status=Available (or any status) to filter the queryset.
    Used by the Lease form to show only Available properties when creating a lease.
    """
    serializer_class = PropertyForRentSerializer
    permission_classes = [ReadOnlyOrAuthenticated]  # ✅ changed

    def get_queryset(self):
        queryset = Property.objects.select_related("owner_no", "staff_no", "branch_no").all()
        status_filter = self.request.query_params.get("status")
        if status_filter:
            queryset = queryset.filter(status=status_filter)

        # Public users (unauthenticated) and non-staff should never see 'Pending Approval' or 'Rejected'
        user = self.request.user
        if not user or not user.is_authenticated or not is_staff_user(user):
            queryset = queryset.exclude(status__in=["Pending Approval", "Rejected"])

        return queryset

    def perform_create(self, serializer):
        user = self.request.user

        # Staff/admin can specify owner_no and any status they want
        if is_staff_user(user):
            owner = serializer.validated_data.get("owner_no")
            if owner:
                serializer.save()
                return
            client_profile = get_client_profile_or_error(user)
            serializer.save(owner_no=client_profile)
            return

        # Regular owners: always start as 'Pending Approval'
        client_profile = get_client_profile_or_error(user)
        serializer.save(owner_no=client_profile, status="Pending Approval")


class MyPropertyForRentListView(generics.ListAPIView):
    """
    'My Listings' (owner-only view).
    """
    serializer_class = PropertyForRentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        base_qs = Property.objects.select_related("owner_no", "staff_no", "branch_no")

        client_profile = get_client_profile_or_error(self.request.user)

        # Optional: enforce role if you want
        if getattr(client_profile, "role", None) != "Owner":
            return base_qs.none()

        return base_qs.filter(owner_no=client_profile)


class PropertyForRentDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Property.objects.select_related("owner_no", "staff_no", "branch_no").all()
    serializer_class = PropertyForRentSerializer
    lookup_field = "property_no"
    permission_classes = [ReadOnlyOrAuthenticated]

    def perform_update(self, serializer):
        user = self.request.user
        instance = self.get_object()
        
        new_status = serializer.validated_data.get("status")

        if is_staff_user(user):
            # Staff cannot manually mark a property as Rented unless it is already Rented
            if new_status == "Rented" and instance.status != "Rented":
                raise serializers.ValidationError({"detail": "You cannot manually mark a property as Rented. Please create a Lease Agreement instead."})
        else:
            client_profile = get_client_profile_or_error(user)
            if instance.owner_no != client_profile:
                raise serializers.ValidationError({"detail": "You do not have permission to edit this property."})

            if new_status and new_status != instance.status:
                if new_status == "Withdrawn":
                    if instance.status not in ["Pending Approval", "Available", "Rejected"]:
                        raise serializers.ValidationError({"detail": "You cannot withdraw a property that is already rented or withdrawn."})
                elif new_status == "Pending Approval":
                    if instance.status != "Rejected":
                        raise serializers.ValidationError({"detail": "You can only re-submit rejected properties for approval."})
                else:
                    raise serializers.ValidationError({"detail": "You are not authorized to set this status."})

        serializer.save()

    def perform_destroy(self, instance):
        user = self.request.user
        if not is_staff_user(user):
            client_profile = get_client_profile_or_error(user)
            if instance.owner_no != client_profile:
                raise serializers.ValidationError({"detail": "You do not have permission to delete this property."})
            
            if instance.status == "Rented":
                raise serializers.ValidationError({"detail": "You cannot delete a property that is currently rented."})
                
        instance.delete()


class PropertyViewingListCreateView(generics.ListCreateAPIView):
    queryset = PropertyViewing.objects.select_related("property_no", "renter_no").all()
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        user = self.request.user
        
        if is_staff_user(user):
            # Staff can schedule viewings on behalf of a renter
            # The renter_no is read from the POST payload by the serializer
            if "renter_no" not in serializer.validated_data:
                raise serializers.ValidationError({"renter_no": "This field is required when staff schedules a viewing."})
            serializer.save(status=PropertyViewing.ViewingStatus.REQUESTED)
            return

        # Regular renters can only schedule for themselves
        client_profile = get_client_profile_or_error(user)
        if getattr(client_profile, "role", None) != "Renter":
            raise serializers.ValidationError({"detail": "Only renters can request viewings."})

        serializer.save(
            renter_no=client_profile,
            status=PropertyViewing.ViewingStatus.REQUESTED,
        )


class MyPropertyViewingListView(generics.ListAPIView):
    """
    Returns only the viewings that belong to the currently logged-in renter.
    GET /api/properties/viewings/my/
    """
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        client_profile = get_client_profile_or_error(self.request.user)
        return PropertyViewing.objects.select_related("property_no", "renter_no").filter(
            renter_no=client_profile
        ).order_by("-view_date")


class PropertyViewingDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = PropertyViewing.objects.select_related("property_no", "renter_no").all()
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_update(self, serializer):
        allowed_fields = {"status"}
        for key in list(serializer.validated_data.keys()):
            if key not in allowed_fields:
                serializer.validated_data.pop(key)

        user = self.request.user
        instance = self.get_object()

        if is_staff_user(user):
            new_status = serializer.validated_data.get("status")
            if new_status not in [
                PropertyViewing.ViewingStatus.APPROVED,
                PropertyViewing.ViewingStatus.REJECTED,
            ]:
                raise serializers.ValidationError({"detail": "Staff can only approve or reject viewings."})

            staff_profile = getattr(user, "staff_profile", None)
            serializer.save(
                status=new_status,
                decided_by=staff_profile,
                decided_at=timezone.now(),
            )
            return

        client_profile = get_client_profile_or_error(user)
        if instance.renter_no != client_profile:
            raise serializers.ValidationError({"detail": "You can only update your own viewing requests."})

        new_status = serializer.validated_data.get("status")
        if new_status != PropertyViewing.ViewingStatus.CANCELLED:
            raise serializers.ValidationError({"detail": "Renters can only cancel their own viewings."})

        if instance.status != PropertyViewing.ViewingStatus.REQUESTED:
            raise serializers.ValidationError({"detail": "Only requested viewings can be cancelled."})

        serializer.save(status=PropertyViewing.ViewingStatus.CANCELLED)


class PropertyInspectionListCreateView(generics.ListCreateAPIView):
    queryset = PropertyInspection.objects.select_related("property_no", "staff_no").all()
    serializer_class = PropertyInspectionSerializer
    permission_classes = [permissions.IsAuthenticated]


class PropertyInspectionDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = PropertyInspection.objects.select_related("property_no", "staff_no").all()
    serializer_class = PropertyInspectionSerializer
    permission_classes = [permissions.IsAuthenticated]


class AdvertisementListCreateView(generics.ListCreateAPIView):
    queryset = Advertisement.objects.select_related("property_no", "assigned_by").all()
    serializer_class = AdvertisementSerializer
    permission_classes = [ReadOnlyOrAuthenticated]

    def perform_create(self, serializer):
        staff_profile = getattr(self.request.user, "staff_profile", None)
        serializer.save(assigned_by=staff_profile)


class AdvertisementDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Advertisement.objects.select_related("property_no", "assigned_by").all()
    serializer_class = AdvertisementSerializer
    permission_classes = [ReadOnlyOrAuthenticated]