# pyrefly: ignore [missing-import]
from rest_framework import generics, serializers, permissions
from django.utils import timezone
# apps/properties/views.py
from .models import Advertisement, Property, PropertyInspection, PropertyViewing
# pyrefly: ignore [missing-import]
from apps.users.models import Client

# ✅ add this import (we created this file already)
from .permissions import ReadOnlyOrAuthenticated

# --- SERIALIZERS ---

class PropertyForRentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Property
        fields = "__all__"
        # property_no is generated by the model
        read_only_fields = ["property_no"]


class PropertyViewingSerializer(serializers.ModelSerializer):
    class Meta:
        model = PropertyViewing
        fields = "__all__"
        read_only_fields = ["renter_no", "decided_by", "decided_at"]


class PropertyInspectionSerializer(serializers.ModelSerializer):
    class Meta:
        model = PropertyInspection
        fields = "__all__"


class AdvertisementSerializer(serializers.ModelSerializer):
    class Meta:
        model = Advertisement
        fields = "__all__"
        read_only_fields = ["assigned_by"]


# --- HELPERS ---

def get_client_profile_or_error(user):
    try:
        return Client.objects.get(user_no=user)
    except Client.DoesNotExist:
        raise serializers.ValidationError(
            {
                "detail": "Your user account is not linked to a Client profile. "
                        "Create a Client record for this user in the Admin panel."
            }
        )


def is_staff_user(user):
    return bool(user and user.is_authenticated and (user.is_superuser or user.is_staff or hasattr(user, "staff_profile")))


# --- VIEWS ---

class PropertyForRentListCreateView(generics.ListCreateAPIView):
    """
    Public READ (GET), authenticated WRITE (POST).
    """
    queryset = Property.objects.select_related("owner_no", "staff_no", "branch_no").all()
    serializer_class = PropertyForRentSerializer
    permission_classes = [ReadOnlyOrAuthenticated]  # ✅ changed

    def perform_create(self, serializer):
        # Allow admin/staff to specify owner_no, otherwise fall back to current client profile.
        owner = serializer.validated_data.get("owner_no")
        if owner:
            serializer.save()
            return

        client_profile = get_client_profile_or_error(self.request.user)
        serializer.save(owner_no=client_profile)


class MyPropertyForRentListView(generics.ListAPIView):
    """
    'My Listings' (owner-only view).
    """
    serializer_class = PropertyForRentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        base_qs = Property.objects.select_related("owner_no", "staff_no", "branch_no")

        client_profile = get_client_profile_or_error(self.request.user)

        # Optional: enforce role if you want
        if getattr(client_profile, "role", None) != "Owner":
            return base_qs.none()

        return base_qs.filter(owner_no=client_profile)


class PropertyForRentDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Property.objects.select_related("owner_no", "staff_no", "branch_no").all()
    serializer_class = PropertyForRentSerializer
    lookup_field = "property_no"
    permission_classes = [ReadOnlyOrAuthenticated]


class PropertyViewingListCreateView(generics.ListCreateAPIView):
    queryset = PropertyViewing.objects.select_related("property_no", "renter_no").all()
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        client_profile = get_client_profile_or_error(self.request.user)
        if getattr(client_profile, "role", None) != "Renter":
            raise serializers.ValidationError({"detail": "Only renters can request viewings."})

        serializer.save(
            renter_no=client_profile,
            status=PropertyViewing.ViewingStatus.REQUESTED,
        )


class MyPropertyViewingListView(generics.ListAPIView):
    """
    Returns only the viewings that belong to the currently logged-in renter.
    GET /api/properties/viewings/my/
    """
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        client_profile = get_client_profile_or_error(self.request.user)
        return PropertyViewing.objects.select_related("property_no", "renter_no").filter(
            renter_no=client_profile
        ).order_by("-view_date")


class PropertyViewingDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = PropertyViewing.objects.select_related("property_no", "renter_no").all()
    serializer_class = PropertyViewingSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_update(self, serializer):
        allowed_fields = {"status"}
        for key in list(serializer.validated_data.keys()):
            if key not in allowed_fields:
                serializer.validated_data.pop(key)

        user = self.request.user
        instance = self.get_object()

        if is_staff_user(user):
            new_status = serializer.validated_data.get("status")
            if new_status not in [
                PropertyViewing.ViewingStatus.APPROVED,
                PropertyViewing.ViewingStatus.REJECTED,
            ]:
                raise serializers.ValidationError({"detail": "Staff can only approve or reject viewings."})

            staff_profile = getattr(user, "staff_profile", None)
            serializer.save(
                status=new_status,
                decided_by=staff_profile,
                decided_at=timezone.now(),
            )
            return

        client_profile = get_client_profile_or_error(user)
        if instance.renter_no != client_profile:
            raise serializers.ValidationError({"detail": "You can only update your own viewing requests."})

        new_status = serializer.validated_data.get("status")
        if new_status != PropertyViewing.ViewingStatus.CANCELLED:
            raise serializers.ValidationError({"detail": "Renters can only cancel their own viewings."})

        if instance.status != PropertyViewing.ViewingStatus.REQUESTED:
            raise serializers.ValidationError({"detail": "Only requested viewings can be cancelled."})

        serializer.save(status=PropertyViewing.ViewingStatus.CANCELLED)


class PropertyInspectionListCreateView(generics.ListCreateAPIView):
    queryset = PropertyInspection.objects.select_related("property", "staff").all()
    serializer_class = PropertyInspectionSerializer
    permission_classes = [permissions.IsAuthenticated]


class PropertyInspectionDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = PropertyInspection.objects.select_related("property", "staff").all()
    serializer_class = PropertyInspectionSerializer
    permission_classes = [permissions.IsAuthenticated]


class AdvertisementListCreateView(generics.ListCreateAPIView):
    queryset = Advertisement.objects.select_related("property_no", "assigned_by").all()
    serializer_class = AdvertisementSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        staff_profile = getattr(self.request.user, "staff_profile", None)
        serializer.save(assigned_by=staff_profile)


class AdvertisementDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Advertisement.objects.select_related("property_no", "assigned_by").all()
    serializer_class = AdvertisementSerializer
    permission_classes = [permissions.IsAuthenticated]