# Generated by Django 6.0.3 on 2026-03-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('lease_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('rent_start', models.DateField()),
                ('rent_finish', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.propertyforrent')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='users.renter')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arranged_leases', to='users.staff')),
            ],
        ),
    ]
