# Generated by Django 6.0.3 on 2026-04-08 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0002_propertyforrent_date_withdrawn_and_more'),
        ('users', '0003_remove_client_birthdate_remove_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='duration',
            field=models.IntegerField(help_text='Duration in months', validators=[django.core.validators.MinValueValidator(3, message='Minimum lease is 3 months.'), django.core.validators.MaxValueValidator(12, message='Maximum lease is 1 year.')]),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='lease_no',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(limit_choices_to={'status': 'Available'}, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.propertyforrent'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='renter',
            field=models.ForeignKey(limit_choices_to={'role': 'Renter'}, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='users.client'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'position__in': ['Manager', 'Supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arranged_leases', to='users.staff'),
        ),
    ]
