# Generated by Django 6.0.3 on 2026-05-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_leaseagreement_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='property',
            new_name='property_no',
        ),
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='renter',
            new_name='renter_no',
        ),
        migrations.RenameField(
            model_name='leaseagreement',
            old_name='staff',
            new_name='staff_no',
        ),
    ]
