# Generated by Django 6.0.4 on 2026-05-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_rename_property_leaseagreement_property_no_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Drop the existing function to ensure we update the parameter types correctly
DROP FUNCTION IF EXISTS is_property_available_for_lease(VARCHAR, DATE, DATE);

-- 2. Create the function with the corrected column name
CREATE OR REPLACE FUNCTION is_property_available_for_lease(
    p_property_no VARCHAR, 
    p_start_date DATE,
    p_end_date DATE
) RETURNS BOOLEAN AS $$
DECLARE
    v_active_leases INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_active_leases
    FROM leases_leaseagreement
    -- Use the column name suggested by the PostgreSQL hint
    WHERE property_no_id = p_property_no 
      AND (rent_start <= p_end_date AND rent_finish >= p_start_date);

    RETURN v_active_leases = 0;
END;
$$ LANGUAGE plpgsql;"""
        )
    ]