# Generated by Django 6.0.3 on 2026-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_auto_20260506_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaseagreement',
            options={'verbose_name_plural': 'Lease Agreements'},
        ),
        migrations.AlterModelTable(
            name='leaseagreement',
            table='lease_agreement',
        ),
    ]
