# Generated by Django 6.0.3 on 2026-05-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_alter_leaseagreement_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- JL Function 1
                CREATE OR REPLACE FUNCTION fn_trigger_validate_branch()
                RETURNS TRIGGER
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    v_manager_position TEXT;
                BEGIN
                    -- 1. Basic Field Validations
                    IF NULLIF(trim(NEW.street), '') IS NULL THEN
                        RAISE EXCEPTION 'Street is required';
                    END IF;

                    IF NULLIF(trim(NEW.city), '') IS NULL THEN
                        RAISE EXCEPTION 'City is required';
                    END IF;

                    -- 2. Area Validation
                    IF NEW.area IS NOT NULL AND NEW.area NOT IN ('Carmen', 'Lapasan', 'Macasandig', 'Poblacion', 'Lumbia') THEN
                        RAISE EXCEPTION 'Invalid area: %', NEW.area;
                    END IF;

                    -- 3. Pattern Matching
                    IF NEW.postcode IS NULL OR NEW.postcode !~ '^[A-Za-z0-9 -]{3,20}$' THEN
                        RAISE EXCEPTION 'Invalid postcode format';
                    END IF;

                    IF NEW.telephone_no IS NULL OR NEW.telephone_no !~ '^\+?[0-9()[:space:]-]{7,50}$' THEN
                        RAISE EXCEPTION 'Invalid telephone format';
                    END IF;

                    -- 4. Manager Check (UPDATED COLUMN NAME HERE)
                    IF NEW.manager_no_id IS NOT NULL THEN  -- Changed from manager_no to manager_no_id
                        SELECT position 
                        INTO v_manager_position
                        FROM staff 
                        WHERE staff_no = NEW.manager_no_id; -- Changed from manager_no to manager_no_id

                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Manager % does not exist', NEW.manager_no_id;
                        ELSIF v_manager_position <> 'Manager' THEN
                            RAISE EXCEPTION 'Staff % is not a Manager', NEW.manager_no_id;
                        END IF;
                    END IF;

                    RETURN NEW;
                END;
                $$;

                -- Drop existing trigger to prevent duplication errors
                DROP TRIGGER IF EXISTS trg_validate_branch_before_insert_update ON branch;

                -- Recreate the trigger attached to the 'branch' table
                CREATE TRIGGER trg_validate_branch_before_insert_update
                BEFORE INSERT OR UPDATE ON branch
                FOR EACH ROW
                EXECUTE FUNCTION fn_trigger_validate_branch();
                                
            """
        )
    ]


