# Generated by Django 6.0.3 on 2026-05-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_auto_20260510_1950'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- ==========================================
            -- 1. THE BRAIN (Trigger Function)
            -- Handles validations and business rules
            -- ==========================================
            CREATE OR REPLACE FUNCTION validate_lease_data()
            RETURNS TRIGGER AS $$
            BEGIN
                -- Prevent illogical lease durations
                IF NEW.rent_finish <= NEW.rent_start THEN
                    RAISE EXCEPTION 'Invalid Contract: Lease finish date must be strictly after the start date.';
                END IF;

                -- Enforce DreamHome Policy: Duration must be between 3 and 12 months
                IF NEW.duration < 3 OR NEW.duration > 12 THEN
                    RAISE EXCEPTION 'DreamHome Policy Violation: Lease duration must be between 3 and 12 months.';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- ==========================================
            -- 2. THE MOTION SENSOR (Trigger)
            -- ==========================================
            DROP TRIGGER IF EXISTS trg_validate_lease ON lease_agreement;
            
            CREATE TRIGGER trg_validate_lease
            BEFORE INSERT OR UPDATE ON lease_agreement
            FOR EACH ROW
            EXECUTE FUNCTION validate_lease_data();

            -- ==========================================
            -- 3. THE INTEGRATED PROCEDURE
            -- Handles Concurrency, Insertion, and Property Update
            -- ==========================================
            CREATE OR REPLACE PROCEDURE create_lease_agreement(
                p_lease_no VARCHAR,
                p_renter_no VARCHAR,
                p_property_no VARCHAR,
                p_staff_no VARCHAR,
                p_monthly_rent NUMERIC,
                p_payment_method VARCHAR,
                p_deposit NUMERIC,
                p_deposit_paid BOOLEAN,
                p_rent_start DATE,
                p_rent_finish DATE,
                p_duration INT,
                p_is_renewal BOOLEAN DEFAULT FALSE,
                p_has_rule_violations BOOLEAN DEFAULT FALSE
            )
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_active_leases INT;
            BEGIN
                -- STEP 1: RENEWAL POLICY CHECK
                IF p_is_renewal AND p_has_rule_violations THEN
                    RAISE EXCEPTION 'Contract renewal rejected: Tenant has recorded rule violations.';
                END IF;

                -- STEP 2: CONCURRENCY LOCK
                -- Lock the property row so no other agent can lease it at this exact moment
                PERFORM 1 
                FROM property 
                WHERE property_no = p_property_no 
                FOR UPDATE;

                -- STEP 3: OVERLAP CHECK
                -- Check if this property already has an active lease overlapping these dates
                SELECT COUNT(*) INTO v_active_leases
                FROM lease_agreement
                WHERE property_no_id = p_property_no
                  AND (rent_start <= p_rent_finish AND rent_finish >= p_rent_start);

                IF v_active_leases > 0 THEN
                    RAISE EXCEPTION 'Double-booking prevented: This property already has an active lease during this timeframe.';
                END IF;

                -- STEP 4: THE INSERT
                -- Using the exact _id columns as generated by Django
                INSERT INTO lease_agreement (
                    lease_no, monthly_rent, payment_method, deposit, deposit_paid, 
                    rent_start, rent_finish, duration, property_no_id, renter_no_id, staff_no_id
                ) VALUES (
                    p_lease_no, p_monthly_rent, p_payment_method, p_deposit, p_deposit_paid,
                    p_rent_start, p_rent_finish, p_duration, p_property_no, p_renter_no, p_staff_no
                );

                -- STEP 5: UPDATE PROPERTY INVENTORY
                -- Automatically update the property status to 'Leased'
                UPDATE property 
                SET status = 'Leased' 
                WHERE property_no = p_property_no;

                -- STEP 6: IMPLICIT COMMIT
                -- Transaction safely commits here, releasing the lock.
            END;
            $$;
            """
        ),
    ]
