# Generated by Django 6.0.3 on 2026-05-04 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0003_rename_property_leaseagreement_property_no_and_more'),
        ('users', '0009_alter_client_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_no', models.CharField(editable=False, help_text='Unique payment identifier.', max_length=20, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Credit/Debit Card'), ('Transfer', 'Bank Transfer'), ('Check', 'Check')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('lease', models.ForeignKey(db_column='lease_no', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='leases.leaseagreement')),
                ('processed_by_staff', models.ForeignKey(blank=True, db_column='processed_by_staff_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='users.staff')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
