# Generated by Django 6.0.4 on 2026-05-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20260506_0006'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION get_active_property_count()
RETURNS INTEGER AS $$
DECLARE
    active_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO active_count
    FROM properties_property
    WHERE status != 'Withdrawn';
    
    RETURN active_count;
END;
$$ LANGUAGE plpgsql;

SELECT get_active_property_count();
            """
        )
    ]

