# Generated by Django 6.0.4 on 2026-05-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20260506_0831'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION get_property_details(p_property_no VARCHAR)
RETURNS TABLE (
    property_no   VARCHAR,
    title         VARCHAR,
    property_type VARCHAR,
    monthly_rent  DECIMAL,
    full_address  TEXT,
    status        VARCHAR,
    no_of_rooms   INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.property_no,
        p.title,
        p.property_type,
        p.monthly_rent,
        CONCAT(p.street, ', ', COALESCE(p.area, ''), ', ', p.city, ' ', p.postcode)::TEXT AS full_address,
        p.status,
        p.no_of_rooms
    FROM properties_property p
    WHERE p.property_no = p_property_no;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Property % not found.', p_property_no;
    END IF;
END;
$$ LANGUAGE plpgsql;
"""
        )
    ]
