# Generated by Django 6.0.4 on 2026-05-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20260506_0833'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Drop the function first to ensure a clean update
DROP FUNCTION IF EXISTS calculate_outstanding_balance(VARCHAR);

CREATE OR REPLACE FUNCTION calculate_outstanding_balance(p_lease_no VARCHAR)
RETURNS NUMERIC AS $$
DECLARE
    v_total_due  NUMERIC;
    v_total_paid NUMERIC;
BEGIN
    -- Get total due from the lease table
    SELECT (monthly_rent * duration)
      INTO v_total_due
      FROM leases_leaseagreement
     WHERE lease_no = p_lease_no;

    -- FIX: Use "lease_no" instead of "lease_no_id" 
    -- as per the HINT in your error message
    SELECT COALESCE(SUM(amount_paid), 0)
      INTO v_total_paid
      FROM payment  
     WHERE lease_no = p_lease_no;

    RETURN COALESCE(v_total_due, 0) - v_total_paid;
END;
$$ LANGUAGE plpgsql;
"""
)
    ]
