# Generated by Django 6.0.3 on 2026-05-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20260506_1027'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 🌟 1. CREATE SEQUENCES
            CREATE SEQUENCE IF NOT EXISTS branch_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS staff_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS client_renter_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS client_owner_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS property_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS lease_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS payment_seq START 1;

            -- 🌟 2. INDIVIDUAL GENERATOR FUNCTIONS (Zero-padding removed)

            -- Branch ID Generator (B1, B2...)
            CREATE OR REPLACE FUNCTION generate_branch_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.branch_no IS NULL OR NEW.branch_no = '' THEN
                    NEW.branch_no := 'B' || nextval('branch_seq')::TEXT;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Staff ID Generator (SL1, SL2...)
            CREATE OR REPLACE FUNCTION generate_staff_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.staff_no IS NULL OR NEW.staff_no = '' THEN
                    NEW.staff_no := 'SL' || nextval('staff_seq')::TEXT;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Client ID Generator (CR1, CO1...)
            CREATE OR REPLACE FUNCTION generate_client_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.client_no IS NULL OR NEW.client_no = '' THEN
                    IF NEW.role = 'Renter' THEN
                        NEW.client_no := 'CR' || nextval('client_renter_seq')::TEXT;
                    ELSE
                        NEW.client_no := 'CO' || nextval('client_owner_seq')::TEXT;
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Property ID Generator (PG1, PG2...)
            CREATE OR REPLACE FUNCTION generate_property_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.property_no IS NULL OR NEW.property_no = '' THEN
                    NEW.property_no := 'PG' || nextval('property_seq')::TEXT;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Lease ID Generator (LS1, LS2...)
            CREATE OR REPLACE FUNCTION generate_lease_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.lease_no IS NULL OR NEW.lease_no = '' THEN
                    NEW.lease_no := 'LS' || nextval('lease_seq')::TEXT;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Payment ID Generator (P1, P2...) 
            CREATE OR REPLACE FUNCTION generate_payment_id()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.payment_no IS NULL OR NEW.payment_no = '' THEN
                    NEW.payment_no := 'P' || nextval('payment_seq')::TEXT;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- 🌟 3. CLEANUP AND APPLY TRIGGERS
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON client;
            
            -- 👇 FIX: Table name corrected here
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON property;
            
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON lease_agreement;
            DROP TRIGGER IF EXISTS trigger_generate_payment_id ON payment;

            CREATE TRIGGER trigger_generate_branch_id BEFORE INSERT ON branch FOR EACH ROW EXECUTE FUNCTION generate_branch_id();
            CREATE TRIGGER trigger_generate_staff_id BEFORE INSERT ON staff FOR EACH ROW EXECUTE FUNCTION generate_staff_id();
            CREATE TRIGGER trigger_generate_client_id BEFORE INSERT ON client FOR EACH ROW EXECUTE FUNCTION generate_client_id();
            
            -- 👇 FIX: Table name corrected here
            CREATE TRIGGER trigger_generate_property_id BEFORE INSERT ON property FOR EACH ROW EXECUTE FUNCTION generate_property_id();
            
            CREATE TRIGGER trigger_generate_lease_id BEFORE INSERT ON lease_agreement FOR EACH ROW EXECUTE FUNCTION generate_lease_id();
            CREATE TRIGGER trigger_generate_payment_id BEFORE INSERT ON payment FOR EACH ROW EXECUTE FUNCTION generate_payment_id();
            """,
            
            reverse_sql="""
            -- Remove Triggers
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON client;
            
            -- 👇 FIX: Table name corrected here
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON property;
            
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON lease_agreement;
            DROP TRIGGER IF EXISTS trigger_generate_payment_id ON payment;
            
            -- Remove Individual Functions
            DROP FUNCTION IF EXISTS generate_branch_id();
            DROP FUNCTION IF EXISTS generate_staff_id();
            DROP FUNCTION IF EXISTS generate_client_id();
            DROP FUNCTION IF EXISTS generate_property_id();
            DROP FUNCTION IF EXISTS generate_lease_id();
            DROP FUNCTION IF EXISTS generate_payment_id();
            
            -- Remove Sequences
            DROP SEQUENCE IF EXISTS branch_seq;
            DROP SEQUENCE IF EXISTS staff_seq;
            DROP SEQUENCE IF EXISTS client_renter_seq;
            DROP SEQUENCE IF EXISTS client_owner_seq;
            DROP SEQUENCE IF EXISTS property_seq;
            DROP SEQUENCE IF EXISTS lease_seq;
            DROP SEQUENCE IF EXISTS payment_seq;
            """
        )
    ]