# Generated by Django 6.0.3 on 2026-05-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20260507_2125'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION get_active_property_count()
            RETURNS INTEGER AS $$
            DECLARE
                active_count INTEGER;
            BEGIN
                SELECT COUNT(*) INTO active_count
                FROM property
                WHERE status != 'Withdrawn';
                
                RETURN active_count;
            END;
            $$ LANGUAGE plpgsql;
            -- SELECT get_active_property_count();
            
            -- 2. CREATE FUNCTION TO GET PROPERTY DETAILS BY ID
            CREATE OR REPLACE FUNCTION get_property_details(p_property_no VARCHAR)
            RETURNS TABLE (
                property_no   VARCHAR,
                title         VARCHAR,
                property_type VARCHAR,
                monthly_rent  DECIMAL,
                full_address  TEXT,
                status        VARCHAR,
                no_of_rooms   INTEGER
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT
                    p.property_no,
                    p.title,
                    p.property_type,
                    p.monthly_rent,
                    CONCAT(p.street, ', ', COALESCE(p.area, ''), ', ', p.city, ' ', p.postcode)::TEXT AS full_address,
                    p.status,
                    p.no_of_rooms
                FROM property p
                WHERE p.property_no = p_property_no;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Property % not found.', p_property_no;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            
            -- 3.  Drop the function first to ensure a clean update
            DROP FUNCTION IF EXISTS calculate_outstanding_balance(VARCHAR);

            CREATE OR REPLACE FUNCTION calculate_outstanding_balance(p_lease_no VARCHAR)
            RETURNS NUMERIC AS $$
            DECLARE
                v_total_due  NUMERIC;
                v_total_paid NUMERIC;
            BEGIN
                -- Get total due from the lease table
                SELECT (monthly_rent * duration)
                INTO v_total_due
                FROM lease_agreement
                WHERE lease_no = p_lease_no;

                -- FIX: Use "lease_no" instead of "lease_no_id" 
                -- as per the HINT in your error message
                SELECT COALESCE(SUM(amount_paid), 0)
                INTO v_total_paid
                FROM payment  
                WHERE lease_no = p_lease_no;

                RETURN COALESCE(v_total_due, 0) - v_total_paid;
            END;
            $$ LANGUAGE plpgsql;
            
            -- 4. 
            CREATE OR REPLACE FUNCTION auto_set_date_withdrawn()
            RETURNS TRIGGER AS $$
            BEGIN
                -- When status changes TO 'Withdrawn', record today's date
                IF NEW.status = 'Withdrawn' AND (OLD.status IS DISTINCT FROM 'Withdrawn') THEN
                    NEW.date_withdrawn := CURRENT_DATE;
                -- When status changes FROM 'Withdrawn' back to something else, clear the date
                ELSIF OLD.status = 'Withdrawn' AND NEW.status != 'Withdrawn' THEN
                    NEW.date_withdrawn := NULL;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            DROP TRIGGER IF EXISTS trigger_auto_date_withdrawn ON property;
            CREATE TRIGGER trigger_auto_date_withdrawn
            BEFORE UPDATE ON property
            FOR EACH ROW EXECUTE FUNCTION auto_set_date_withdrawn();
            
            -- 5. 
            DROP FUNCTION IF EXISTS get_owner_property_count(VARCHAR);
            CREATE OR REPLACE FUNCTION get_owner_property_count(p_owner_id VARCHAR)
            RETURNS INTEGER AS $$
            DECLARE
                v_count INTEGER;
            BEGIN
                -- Directly count properties for the specific owner_id
                SELECT COUNT(*) INTO v_count
                FROM property
                WHERE owner_id = p_owner_id;
                
                RETURN v_count;
            END;
            $$ LANGUAGE plpgsql;
            
            -- 6. 
            DROP FUNCTION IF EXISTS is_property_available_for_lease(VARCHAR, DATE, DATE);
            CREATE OR REPLACE FUNCTION is_property_available_for_lease(
                p_property_no VARCHAR, 
                p_start_date DATE,
                p_end_date DATE
            ) RETURNS BOOLEAN AS $$
            DECLARE
                v_active_leases INTEGER;
            BEGIN
                SELECT COUNT(*) INTO v_active_leases
                FROM lease_agreement
                WHERE property_no_id = p_property_no 
                AND (rent_start <= p_end_date AND rent_finish >= p_start_date);

                RETURN v_active_leases = 0;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    ]
