# Generated by Django 6.0.3 on 2026-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20260507_2152'),
        ('payments', '0008_auto_20260508_1556'),
    ]

    operations = [
    ]
