# Generated by Django 6.0.3 on 2026-05-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_merge_0007_auto_20260507_2152_0008_auto_20260508_1556'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Function to check balance before allowing a payment
            CREATE OR REPLACE FUNCTION fn_prevent_overpayment()
            RETURNS TRIGGER AS $$
            DECLARE
                v_balance NUMERIC;
            BEGIN
                -- Use the function we migrated earlier
                v_balance := calculate_outstanding_balance(NEW.lease_no);

                -- Validation logic
                IF NEW.amount_paid > v_balance THEN
                    RAISE EXCEPTION 'Invalid Payment: % exceeds the outstanding balance (%) for lease %', 
                        NEW.amount_paid, v_balance, NEW.lease_no;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- 2. Attach the trigger to the payment table
            DROP TRIGGER IF EXISTS trg_check_overpayment ON payment;
            CREATE TRIGGER trg_check_overpayment
            BEFORE INSERT ON payment
            FOR EACH ROW
            EXECUTE FUNCTION fn_prevent_overpayment();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_check_overpayment ON payment;
            DROP FUNCTION IF EXISTS fn_prevent_overpayment();
            """
        ),
    ]