# Generated by Django 6.0.3 on 2026-05-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20260508_1626'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE PROCEDURE process_rental_payment(
                p_lease_no VARCHAR,
                p_amount NUMERIC,
                p_method VARCHAR,
                p_staff_no VARCHAR
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                -- Inserting into the payment table
                -- Note: staff_no_id is the standard Django FK name
                INSERT INTO payment (
                    lease_no,
                    amount_paid,
                    payment_method,
                    processed_by_staff_no,
                    payment_date
                )
                VALUES (
                    p_lease_no,
                    p_amount,
                    p_method,
                    p_staff_no,
                    CURRENT_TIMESTAMP
                );
            END;
            $$;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS process_rental_payment(VARCHAR, NUMERIC, VARCHAR, VARCHAR);"
        ),
    ]