# Generated by Django 6.0.3 on 2026-05-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20260508_1643'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE PROCEDURE process_rental_payment(
                p_lease_no VARCHAR,
                p_amount NUMERIC,
                p_method VARCHAR,
                p_staff_no VARCHAR
            )
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_check_lease VARCHAR;
            BEGIN
                -- 1. CONCURRENCY & TRANSACTION CONTROL
                -- This locks the lease row so no other process can touch it.
                -- It also verifies that the staff 'p_staff_no' is the one assigned.
                SELECT lease_no INTO v_check_lease
                FROM lease_agreement
                WHERE lease_no = p_lease_no 
                    AND staff_no_id = p_staff_no
                FOR UPDATE;

                -- 2. VALIDATION
                -- If no row was found, v_check_lease will be NULL
                IF v_check_lease IS NULL THEN
                    RAISE EXCEPTION 'Access Denied: Staff % is not assigned to Lease %', p_staff_no, p_lease_no;
                END IF;

                -- 3. THE ACTION (INSERT)
                INSERT INTO payment (
                    lease_no,
                    amount_paid,
                    payment_method,
                    staff_no_id,
                    payment_date
                )
                VALUES (
                    p_lease_no,
                    p_amount,
                    p_method,
                    p_staff_no,
                    CURRENT_TIMESTAMP
                );
                
                -- Note: The TRIGGER fn_prevent_overpayment still runs here 
                -- automatically to check if the balance is exceeded!
            END;
            $$;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS process_rental_payment(VARCHAR, NUMERIC, VARCHAR, VARCHAR);"
        ),
    ]