# Generated by Django 6.0.3 on 2026-05-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20260508_1704'),
    ]

operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION get_branch_monthly_revenue(p_branch_no VARCHAR, p_year INT, p_month INT)
            RETURNS NUMERIC AS $$
            DECLARE
                v_total_revenue NUMERIC;
            BEGIN
                SELECT COALESCE(SUM(p.amount_paid), 0)
                    INTO v_total_revenue
                    FROM payment p
                    JOIN lease_agreement l ON p.lease_no = l.lease_no
                    JOIN property prop ON l.property_no_id = prop.property_no
                    WHERE prop.branch_no_id = p_branch_no
                    AND EXTRACT(YEAR FROM p.payment_date) = p_year
                    AND EXTRACT(MONTH FROM p.payment_date) = p_month;

                RETURN v_total_revenue;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS get_branch_monthly_revenue(VARCHAR, INT, INT);"
        ),
    ]
