# Generated by Django 6.0.3 on 2026-05-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20260508_1710'),
    ]

operations = [
        migrations.RunSQL(
            sql="""
            -- TRIGGER 1: DEFAULT STATUS
            CREATE OR REPLACE FUNCTION set_default_payment_status()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.status IS NULL OR btrim(NEW.status) = '' THEN
                    NEW.status := 'Completed';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_set_default_payment_status ON payment;
            CREATE TRIGGER trg_set_default_payment_status
            BEFORE INSERT ON payment
            FOR EACH ROW
            EXECUTE FUNCTION set_default_payment_status();

            -- TRIGGER 2: DATA VALIDATION FOR REPORTING
            CREATE OR REPLACE FUNCTION validate_payment_for_reporting()
            RETURNS TRIGGER AS $$
            DECLARE
                v_start  DATE;
                v_finish DATE;
            BEGIN
                -- 1) Amount must be positive
                IF NEW.amount_paid IS NULL OR NEW.amount_paid <= 0 THEN
                    RAISE EXCEPTION 'Payment amount must be greater than 0.';
                END IF;

                -- 2) Payment date must exist
                IF NEW.payment_date IS NULL THEN
                    RAISE EXCEPTION 'Payment date is required.';
                END IF;

                -- 3) Lease must exist and payment_date must be within lease period
                SELECT rent_start, rent_finish
                    INTO v_start, v_finish
                    FROM lease_agreement
                    WHERE lease_no = NEW.lease_no;

                IF v_start IS NULL OR v_finish IS NULL THEN
                    RAISE EXCEPTION 'Lease % not found (or missing dates).', NEW.lease_no;
                END IF;

                IF NEW.payment_date::date < v_start OR NEW.payment_date::date > v_finish THEN
                    RAISE EXCEPTION
                        'Payment date % must be within lease period (% to %).',
                        NEW.payment_date::date, v_start, v_finish;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_validate_payment_for_reporting ON payment;
            CREATE TRIGGER trg_validate_payment_for_reporting
            BEFORE INSERT OR UPDATE ON payment
            FOR EACH ROW
            EXECUTE FUNCTION validate_payment_for_reporting();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_validate_payment_for_reporting ON payment;
            DROP FUNCTION IF EXISTS validate_payment_for_reporting();
            DROP TRIGGER IF EXISTS trg_set_default_payment_status ON payment;
            DROP FUNCTION IF EXISTS set_default_payment_status();
            """
        ),
    ]