# Generated by Django 6.0.3 on 2026-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20260508_1715'),
    ]

operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE PROCEDURE apply_monthly_late_fees(p_fee NUMERIC DEFAULT 50.00)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                -- Insert a penalty record for leases that are behind on payments
                INSERT INTO payment (lease_no, amount_paid, payment_method, payment_date, status, processed_by_staff_no)
                SELECT 
                    l.lease_no, 
                    (p_fee * -1), -- Negative amount increases the 'outstanding balance'
                    'Late Fee Penalty', 
                    CURRENT_TIMESTAMP, 
                    'Penalty',
                    l.staff_no_id
                FROM lease_agreement l
                WHERE CURRENT_DATE <= l.rent_finish
                  -- Check if the sum of their payments is less than (monthly_rent * months_passed)
                    AND calculate_outstanding_balance(l.lease_no) > 0; 
            END;
            $$;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS apply_monthly_late_fees(NUMERIC);"
        ),
    ]
