# Generated by Django 6.0.3 on 2026-05-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20260508_1731'),
    ]

    operations = [
        migrations.RunSQL(
    sql="""
    CREATE OR REPLACE PROCEDURE transfer_payment_correction(
        p_payment_id INT, 
        p_wrong_lease VARCHAR, 
        p_correct_lease VARCHAR,
        p_staff_id VARCHAR
    )
    LANGUAGE plpgsql
    AS $$
    BEGIN
        -- 1. CONCURRENCY CONTROL: Lock both leases to prevent balance shifts during transfer
        PERFORM lease_no FROM lease_agreement 
        WHERE lease_no IN (p_wrong_lease, p_correct_lease) 
        FOR UPDATE;

        -- 2. TRANSACTION LOGIC: Update the payment record
        UPDATE payment
        SET lease_no = p_correct_lease,
            payment_method = 'Correction Transfer',
            staff_no_id = p_staff_id
        WHERE payment_no = p_payment_id -- Ensure this matches your PK column name
            AND lease_no = p_wrong_lease;

        -- Note: We don't need to manually update "total_paid" because our 
        -- calculate_outstanding_balance function will see the change automatically!
        
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Payment ID % not found for Lease %', p_payment_id, p_wrong_lease;
        END IF;
    END;
    $$;
    """,
    reverse_sql="DROP PROCEDURE IF EXISTS transfer_payment_correction(INT, VARCHAR, VARCHAR, VARCHAR);"
)
    ]
