# Generated by Django 6.0.3 on 2026-05-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20260508_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(blank=True, editable=False, help_text='Unique payment identifier.', max_length=20, primary_key=True, serialize=False),
        ),
    ]
