# Generated by Django 6.0.3 on 2026-03-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('telephone_no', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nin', models.CharField(max_length=50, verbose_name='National Insurance Number')),
                ('position', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_joined', models.DateField()),
                ('typing_speed', models.IntegerField(blank=True, help_text='Secretarial staff only', null=True)),
                ('manager_start_date', models.DateField(blank=True, help_text='Managers only', null=True)),
                ('bonus_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='branches.branch')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('owner_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('telephone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('renter_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('telephone_no', models.CharField(max_length=50)),
                ('pref_property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='next_of_kin', serialize=False, to='users.staff')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('telephone_no', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Next of Kin',
            },
        ),
    ]
