# Generated by Django 6.0.3 on 2026-04-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='The supervisor overseeing this staff member.', limit_choices_to={'position__icontains': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staff'),
        ),
    ]
