# Generated by Django 6.0.3 on 2026-04-08 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_nextofkin_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.AddField(
            model_name='renterrequirement',
            name='general_comments',
            field=models.TextField(blank=True, null=True, verbose_name='General Comments'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_no',
            field=models.CharField(blank=True, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('Renter', 'Renter'), ('Owner', 'Property Owner')], default='Renter', help_text='Determines their permissions and workflows.', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The Django User account tied to this client for login.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='renterrequirement',
            name='pref_property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Flat', 'Flat')], help_text='Select House or Flat.', max_length=50, null=True, verbose_name='Preferred Property Type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Staff', 'Standard Staff'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Secretary', 'Secretarial Staff')], default='Staff', help_text='Select the official job title.', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_no',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='The supervisor overseeing this staff member.', limit_choices_to={'position': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='typing_speed',
            field=models.IntegerField(blank=True, help_text='Secretarial staff only (Words Per Minute).', null=True, validators=[django.core.validators.MinValueValidator(10, message='Typing speed must be at least 10 WPM.'), django.core.validators.MaxValueValidator(250, message='Typing speed cannot exceed 250 WPM.')]),
        ),
        migrations.AddConstraint(
            model_name='renterrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('pref_property_type__in', ['House', 'Flat']), ('pref_property_type__isnull', True), _connector='OR'), name='chk_valid_property_type'),
        ),
    ]
