# Generated by Django 6.0.3 on 2026-04-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_leaseagreement_renter'),
        ('properties', '0002_alter_propertyforrent_owner_and_more'),
        ('users', '0003_client_remove_propertyowner_user_remove_renter_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
