# Generated by Django 6.0.3 on 2026-04-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_client_birthdate_remove_client_gender_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Create or Update the Master Function (Safe because of OR REPLACE)
            CREATE OR REPLACE FUNCTION generate_dreamhome_id()
            RETURNS TRIGGER AS $$
            DECLARE
                prefix TEXT;
                next_num INT;
                id_column TEXT;
            BEGIN
                IF TG_TABLE_NAME = 'branches_branch' THEN
                    prefix := 'B';
                    id_column := 'branch_no';
                ELSIF TG_TABLE_NAME = 'users_staff' THEN
                    prefix := 'SL'; 
                    id_column := 'staff_no';
                ELSIF TG_TABLE_NAME = 'users_client' THEN
                    IF NEW.role = 'Renter' THEN
                        prefix := 'CR';
                    ELSE
                        prefix := 'CO';
                    END IF;
                    id_column := 'client_no';
                ELSIF TG_TABLE_NAME = 'properties_propertyforrent' THEN
                    prefix := 'PG'; 
                    id_column := 'property_no';
                ELSIF TG_TABLE_NAME = 'leases_leaseagreement' THEN
                    prefix := 'LS';
                    id_column := 'lease_no';
                ELSE
                    RETURN NEW; 
                END IF;

                EXECUTE format('SELECT COALESCE(MAX(CAST(SUBSTRING(%I FROM %L) AS INT)), 0) + 1 
                                FROM %I WHERE %I LIKE %L', 
                                id_column, length(prefix) + 1, TG_TABLE_NAME, id_column, prefix || '%')
                INTO next_num;

                IF id_column = 'branch_no' THEN
                    NEW.branch_no := prefix || next_num::TEXT;
                ELSIF id_column = 'staff_no' THEN
                    NEW.staff_no := prefix || next_num::TEXT;
                ELSIF id_column = 'client_no' THEN
                    NEW.client_no := prefix || next_num::TEXT;
                ELSIF id_column = 'property_no' THEN
                    NEW.property_no := prefix || next_num::TEXT;
                ELSIF id_column = 'lease_no' THEN
                    NEW.lease_no := prefix || next_num::TEXT;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- 🌟 2. THE FIX: Drop any existing triggers so they don't conflict
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branches_branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON users_staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON users_client;
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON properties_propertyforrent;
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON leases_leaseagreement;

            -- 3. Create the fresh triggers safely
            CREATE TRIGGER trigger_generate_branch_id BEFORE INSERT ON branches_branch FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_staff_id BEFORE INSERT ON users_staff FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_client_id BEFORE INSERT ON users_client FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_property_id BEFORE INSERT ON properties_propertyforrent FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_lease_id BEFORE INSERT ON leases_leaseagreement FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            """,
            
            reverse_sql="""
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branches_branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON users_staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON users_client;
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON properties_propertyforrent;
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON leases_leaseagreement;
            DROP FUNCTION IF EXISTS generate_dreamhome_id();
            """
        )
    ]