# Generated by Django 6.0.3 on 2026-04-03 09:36

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_propertyowner_delete_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_no',
            field=models.CharField(default=apps.users.utils.generate_client_no, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
