# Generated by Django 6.0.3 on 2026-04-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20260408_2236'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 🌟 1. CREATE SEQUENCES (The Secret to Concurrency Control)
            -- These keep track of the numbers perfectly, even under heavy load.
            CREATE SEQUENCE IF NOT EXISTS branch_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS staff_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS client_renter_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS client_owner_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS property_seq START 1;
            CREATE SEQUENCE IF NOT EXISTS lease_seq START 1;

            -- 🌟 2. UPDATED MASTER FUNCTION
            CREATE OR REPLACE FUNCTION generate_dreamhome_id()
            RETURNS TRIGGER AS $$
            BEGIN
                -- We check if the ID is blank. If it is, we pull the next value safely from the sequence.
                IF TG_TABLE_NAME = 'branches_branch' THEN
                    IF NEW.branch_no IS NULL OR NEW.branch_no = '' THEN
                        NEW.branch_no := 'B' || nextval('branch_seq')::TEXT;
                    END IF;
                    
                ELSIF TG_TABLE_NAME = 'users_staff' THEN
                    IF NEW.staff_no IS NULL OR NEW.staff_no = '' THEN
                        NEW.staff_no := 'SL' || nextval('staff_seq')::TEXT;
                    END IF;
                    
                ELSIF TG_TABLE_NAME = 'users_client' THEN
                    IF NEW.client_no IS NULL OR NEW.client_no = '' THEN
                        IF NEW.role = 'Renter' THEN
                            NEW.client_no := 'CR' || nextval('client_renter_seq')::TEXT;
                        ELSE
                            NEW.client_no := 'CO' || nextval('client_owner_seq')::TEXT;
                        END IF;
                    END IF;
                    
                ELSIF TG_TABLE_NAME = 'properties_propertyforrent' THEN
                    IF NEW.property_no IS NULL OR NEW.property_no = '' THEN
                        NEW.property_no := 'PG' || nextval('property_seq')::TEXT;
                    END IF;
                    
                ELSIF TG_TABLE_NAME = 'leases_leaseagreement' THEN
                    IF NEW.lease_no IS NULL OR NEW.lease_no = '' THEN
                        NEW.lease_no := 'LS' || nextval('lease_seq')::TEXT;
                    END IF;
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- 🌟 3. CLEANUP AND RE-APPLY TRIGGERS
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branches_branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON users_staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON users_client;
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON properties_propertyforrent;
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON leases_leaseagreement;

            CREATE TRIGGER trigger_generate_branch_id BEFORE INSERT ON branches_branch FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_staff_id BEFORE INSERT ON users_staff FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_client_id BEFORE INSERT ON users_client FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_property_id BEFORE INSERT ON properties_propertyforrent FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            CREATE TRIGGER trigger_generate_lease_id BEFORE INSERT ON leases_leaseagreement FOR EACH ROW EXECUTE FUNCTION generate_dreamhome_id();
            """,
            
            reverse_sql="""
            DROP TRIGGER IF EXISTS trigger_generate_branch_id ON branches_branch;
            DROP TRIGGER IF EXISTS trigger_generate_staff_id ON users_staff;
            DROP TRIGGER IF EXISTS trigger_generate_client_id ON users_client;
            DROP TRIGGER IF EXISTS trigger_generate_property_id ON properties_propertyforrent;
            DROP TRIGGER IF EXISTS trigger_generate_lease_id ON leases_leaseagreement;
            DROP FUNCTION IF EXISTS generate_dreamhome_id();
            
            -- Clean up sequences if we roll back
            DROP SEQUENCE IF EXISTS branch_seq;
            DROP SEQUENCE IF EXISTS staff_seq;
            DROP SEQUENCE IF EXISTS client_renter_seq;
            DROP SEQUENCE IF EXISTS client_owner_seq;
            DROP SEQUENCE IF EXISTS property_seq;
            DROP SEQUENCE IF EXISTS lease_seq;
            """
        )
    ]