# Generated by Django 6.0.3 on 2026-04-10 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260410_2056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='renterrequirement',
            name='chk_valid_property_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('Renter', 'Renter'), ('Owner', 'Property Owner')], default='Renter', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='renterrequirement',
            name='general_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renterrequirement',
            name='pref_property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Flat', 'Flat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=10),
        ),
    ]
