# Generated by Django 6.0.3 on 2026-04-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260403_1808'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_client_no()
            RETURNS VARCHAR AS $$
            DECLARE
                today_str VARCHAR(8);
                last_client_no VARCHAR(12);
                new_seq INT;
            BEGIN
                -- 🌟 THE CONCURRENCY CONTROL LOCK 🌟
                -- This forces simultaneous requests into a single-file line
                PERFORM pg_advisory_xact_lock(hashtext('generate_client_no_lock'));

                today_str := to_char(CURRENT_DATE, 'YYYYMMDD');

                SELECT client_no INTO last_client_no
                FROM users_client 
                WHERE client_no LIKE today_str || '%'
                ORDER BY client_no DESC
                LIMIT 1;

                IF last_client_no IS NOT NULL THEN
                    new_seq := CAST(RIGHT(last_client_no, 4) AS INT) + 1;
                ELSE
                    new_seq := 1;
                END IF;

                RETURN today_str || LPAD(new_seq::TEXT, 4, '0');
            END;
            $$ LANGUAGE plpgsql;
            """,
            
            # The reverse is just the function without the lock, in case you undo
            reverse_sql="""
            CREATE OR REPLACE FUNCTION generate_client_no()
            RETURNS VARCHAR AS $$
            DECLARE
                today_str VARCHAR(8);
                last_client_no VARCHAR(12);
                new_seq INT;
            BEGIN
                today_str := to_char(CURRENT_DATE, 'YYYYMMDD');

                SELECT client_no INTO last_client_no
                FROM users_client 
                WHERE client_no LIKE today_str || '%'
                ORDER BY client_no DESC
                LIMIT 1;

                IF last_client_no IS NOT NULL THEN
                    new_seq := CAST(RIGHT(last_client_no, 4) AS INT) + 1;
                ELSE
                    new_seq := 1;
                END IF;

                RETURN today_str || LPAD(new_seq::TEXT, 4, '0');
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    ]