# Generated by Django 6.0.3 on 2026-05-02 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_rename_manager_branch_manager_no'),
        ('users', '0007_remove_renterrequirement_chk_valid_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='user_no',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='staff',
            new_name='staff_no',
        ),
        migrations.RenameField(
            model_name='renterrequirement',
            old_name='client',
            new_name='client_no',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='user_no',
        ),
        migrations.AddField(
            model_name='client',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this client was registered.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='registered_branch',
            field=models.ForeignKey(blank=True, db_column='registering_branch_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='client',
            name='registered_staff',
            field=models.ForeignKey(blank=True, db_column='registering_staff_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to='users.staff'),
        ),
    ]
