# Generated by Django 6.0.3 on 2026-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20260403_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_no',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
