# Generated by Django 6.0.3 on 2026-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_client_user_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registered',
            field=models.DateField(auto_now_add=True, help_text='The date this client was registered.', null=True),
        ),
    ]
