# Generated by Django 6.0.3 on 2026-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_client_date_registered'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='nextofkin',
            table='next_of_kin',
        ),
        migrations.AlterModelTable(
            name='renterrequirement',
            table='renter_requirement',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
