# Generated by Django 6.0.3 on 2026-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_client_table_alter_nextofkin_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='suffixes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='suffixes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='suffixes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
