# Generated by Django 6.0.3 on 2026-05-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_nextofkin_full_name_client_middle_name_and_more'),
    ]

    operations = [
    
        # ==========================================
        # 1. Standard Function: get_properties_by_owner
        # ==========================================
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION get_properties_by_owner(
                    p_owner_no VARCHAR
                )
                RETURNS TABLE (
                    property_no VARCHAR,
                    title VARCHAR,
                    property_type VARCHAR,
                    monthly_rent NUMERIC,
                    status VARCHAR,
                    staff_no VARCHAR
                ) AS $$
                BEGIN
                    RETURN QUERY
                    SELECT 
                        p.property_no,
                        p.title,
                        p.property_type,
                        p.monthly_rent,
                        p.status,
                        p.staff_no
                    -- UPDATED: Removed properties_ prefix to match DB table
                    FROM property p
                    WHERE p.owner_no = p_owner_no
                    ORDER BY p.monthly_rent DESC;

                    IF NOT FOUND THEN
                        RAISE NOTICE 'No properties found for owner %.', p_owner_no;
                    END IF;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS get_properties_by_owner(VARCHAR) CASCADE;",
        ),

        # ==========================================
        # 2. Trigger Function: validate_renter_preferences
        # ==========================================
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION validate_renter_preferences()
                RETURNS TRIGGER AS $$
                DECLARE
                    v_client_role VARCHAR;
                BEGIN
                    -- 1. Ensure the associated client actually has the role of 'Renter'
                    SELECT role INTO v_client_role 
                    -- UPDATED: Removed users_ prefix to match DB table
                    FROM client 
                    WHERE client_no = NEW.client_no;

                    IF v_client_role != 'Renter' THEN
                        RAISE EXCEPTION 'Requirements can only be added for clients with role = Renter. Client % is a(n) %.', NEW.client_no, v_client_role;
                    END IF;

                    -- 2. Validate maximum monthly rent
                    IF NEW.max_monthly_rent IS NOT NULL AND NEW.max_monthly_rent <= 0 THEN
                        RAISE EXCEPTION 'Maximum monthly rent must be greater than zero.';
                    END IF;
                        
                    -- 3. Validate preferred property type
                    IF NEW.pref_property_type IS NOT NULL AND NEW.pref_property_type NOT IN ('Flat', 'House') THEN
                        RAISE EXCEPTION 'Invalid preferred property type. Must be Flat or House.';
                    END IF;
                    
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS validate_renter_preferences() CASCADE;",
        ),

        # ==========================================
        # 3. Trigger Attachment: trigger_check_renter_prefs
        # ==========================================
        migrations.RunSQL(
            # UPDATED: Removed users_ prefix and matched renter_requirement table name
            sql="DROP TRIGGER IF EXISTS trigger_check_renter_prefs ON renter_requirement;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_check_renter_prefs
                -- UPDATED: Removed users_ prefix and matched renter_requirement table name
                BEFORE INSERT OR UPDATE ON renter_requirement
                FOR EACH ROW EXECUTE FUNCTION validate_renter_preferences();
            """,
            # UPDATED: Removed users_ prefix and matched renter_requirement table name
            reverse_sql="DROP TRIGGER IF EXISTS trigger_check_renter_prefs ON renter_requirement;",
        ),
    ]