# Generated by Django 6.0.3 on 2026-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20260510_1819'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE PROCEDURE process_new_lease(
                    p_lease_no VARCHAR,
                    p_property_no VARCHAR,
                    p_renter_no VARCHAR,
                    p_rent_start DATE,
                    p_duration_months INT,
                    p_monthly_rent NUMERIC
                )
                LANGUAGE plpgsql AS $$
                DECLARE
                    v_property_status VARCHAR;
                    v_client_role VARCHAR;
                BEGIN
                    -- 1. Validate duration based on Case Study rules (Min 3, Max 12)
                    IF p_duration_months < 3 OR p_duration_months > 12 THEN
                        RAISE EXCEPTION 'Lease failed: Duration must be between 3 and 12 months.';
                    END IF;

                    -- ==========================================================
                    -- CONCURRENCY CONTROL: Lock the Client Row
                    -- 'FOR SHARE' prevents concurrent transactions from deleting 
                    -- or modifying this client while we verify their role.
                    -- ==========================================================
                    SELECT role INTO v_client_role 
                    FROM client 
                    WHERE client_no = p_renter_no
                    FOR SHARE;

                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Lease failed: Client % does not exist.', p_renter_no;
                    END IF;

                    IF v_client_role != 'Renter' THEN
                        RAISE EXCEPTION 'Lease failed: Client % is a %, not a Renter.', p_renter_no, v_client_role;
                    END IF;

                    -- ==========================================================
                    -- CONCURRENCY CONTROL: Lock the Property Row
                    -- 'FOR UPDATE' exclusively locks this row. If another agent 
                    -- runs this procedure concurrently, they must wait here. 
                    -- This guarantees we never double-book a property.
                    -- ==========================================================
                    SELECT status INTO v_property_status 
                    FROM property 
                    WHERE property_no = p_property_no
                    FOR UPDATE;

                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Lease failed: Property % does not exist.', p_property_no;
                    END IF;

                    IF v_property_status != 'Available' THEN
                        RAISE EXCEPTION 'Lease failed: Property % is currently marked as %, not Available.', p_property_no, v_property_status;
                    END IF;

                    -- 4. Insert the new lease agreement record
                    INSERT INTO lease_agreement (
                        lease_no,
                        property_no, 
                        renter_no, 
                        rent_start, 
                        rent_finish, 
                        duration, 
                        monthly_rent
                    ) VALUES (
                        p_lease_no,
                        p_property_no, 
                        p_renter_no, 
                        p_rent_start, 
                        p_rent_start + (p_duration_months || ' months')::INTERVAL, 
                        p_duration_months,
                        p_monthly_rent
                    );

                    -- 5. Update the property status
                    UPDATE property
                    SET status = 'Rented'
                    WHERE property_no = p_property_no;

                    -- ==========================================================
                    -- TRANSACTION CONTROL: Explicit Commit
                    -- Because this is a PROCEDURE (PostgreSQL 11+), we can explicitly
                    -- commit the transaction. If any RAISE EXCEPTION above is 
                    -- triggered, Postgres skips this and automatically issues a ROLLBACK.
                    -- ==========================================================
                    COMMIT;

                    RAISE NOTICE 'Successfully processed lease % for Property % to Renter %.', p_lease_no, p_property_no, p_renter_no;

                END;
                $$;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS process_new_lease(VARCHAR, VARCHAR, VARCHAR, DATE, INT, NUMERIC);"
        ),
    ]