# Generated by Django 6.0.3 on 2026-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20260510_1828'),
    ]

    operations = [
            migrations.RunSQL(
                sql="""
                    CREATE OR REPLACE PROCEDURE register_client_to_branch(
                        p_client_no VARCHAR,
                        p_branch_no VARCHAR
                    )
                    LANGUAGE plpgsql AS $$
                    DECLARE
                        v_current_branch VARCHAR;
                    BEGIN
                        -- ==========================================================
                        -- 1. CONCURRENCY: Lock the Branch Row (Read Lock)
                        -- 'FOR SHARE' prevents another process from deleting or 
                        -- altering this branch while we are registering a client to it.
                        -- ==========================================================
                        IF NOT EXISTS (SELECT 1 FROM branch WHERE branch_no = p_branch_no FOR SHARE) THEN
                            RAISE EXCEPTION 'Target branch % does not exist.', p_branch_no;
                        END IF;

                        -- ==========================================================
                        -- 2. CONCURRENCY: Lock the Client Row (Write Lock)
                        -- 'FOR UPDATE' exclusively locks this client row. If two 
                        -- staff members try to move the same client simultaneously, 
                        -- the second one is forced to wait in line here.
                        -- ==========================================================
                        SELECT registering_branch_no INTO v_current_branch
                        FROM client
                        WHERE client_no = p_client_no
                        FOR UPDATE;

                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Client % not found.', p_client_no;
                        END IF;

                        -- 3. Only update if they are moving to a NEW branch
                        IF v_current_branch IS DISTINCT FROM p_branch_no THEN
                            UPDATE client
                            SET 
                                registering_branch_no = p_branch_no,
                                -- CRITICAL FIX: Strip away the old staff assignment to prevent cross-branch violations
                                registering_staff_no = NULL 
                            WHERE client_no = p_client_no;
                            
                            -- ==========================================================
                            -- 4. TRANSACTION: Explicit Commit
                            -- Since this is a PROCEDURE, we can explicitly save the state.
                            -- This immediately releases the FOR UPDATE lock safely.
                            -- ==========================================================
                            COMMIT;
                            
                            RAISE NOTICE 'Client % registered to Branch %. Previous staff assignment cleared.', p_client_no, p_branch_no;
                        ELSE
                            -- Release the lock even if we do nothing
                            COMMIT;
                            RAISE NOTICE 'Client % is already registered to Branch %.', p_client_no, p_branch_no;
                        END IF;
                    END;
                    $$;
                """,
                reverse_sql="DROP PROCEDURE IF EXISTS register_client_to_branch(VARCHAR, VARCHAR);"
            ),
        ]
