# Generated by Django 6.0.3 on 2026-05-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20260510_1833'),
    ]

    operations = [
            # ==========================================
            # 1. Function: get_clients_by_staff
            # ==========================================
            migrations.RunSQL(
                sql="""
                    CREATE OR REPLACE FUNCTION get_clients_by_staff(p_staff_no VARCHAR)
                    RETURNS TABLE (
                        client_no VARCHAR,
                        full_name TEXT,
                        role VARCHAR,
                        contact_no VARCHAR
                    ) AS $$
                    BEGIN
                        RETURN QUERY
                        SELECT 
                            c.client_no,
                            (c.first_name || ' ' || c.last_name)::TEXT,
                            c.role,
                            c.telephone_no
                        -- UPDATED: Matched 'client' table name
                        FROM client c
                        WHERE c.registering_staff_no = p_staff_no
                        ORDER BY c.role, c.last_name;
                    END;
                    $$ LANGUAGE plpgsql;
                """,
                reverse_sql="DROP FUNCTION IF EXISTS get_clients_by_staff(VARCHAR) CASCADE;",
            ),

            # ==========================================
            # 2. Trigger Function: auto_update_property_status
            # ==========================================
            migrations.RunSQL(
                sql="""
                    CREATE OR REPLACE FUNCTION auto_update_property_status()
                    RETURNS TRIGGER AS $$
                    BEGIN
                        -- 1. If a new lease is signed, automatically mark the property as 'Rented'
                        IF TG_OP = 'INSERT' THEN
                            -- UPDATED: Matched 'property' table name
                            UPDATE property
                            SET status = 'Rented'
                            WHERE property_no = NEW.property_no;
                            
                        -- 2. If a lease is deleted/cancelled, automatically revert it to 'Available'
                        ELSIF TG_OP = 'DELETE' THEN
                            -- UPDATED: Matched 'property' table name
                            UPDATE property
                            SET status = 'Available'
                            WHERE property_no = OLD.property_no;
                        END IF;

                        -- NOTE: AFTER triggers should return NULL, as the row is already saved.
                        RETURN NULL;
                    END;
                    $$ LANGUAGE plpgsql;
                """,
                reverse_sql="DROP FUNCTION IF EXISTS auto_update_property_status() CASCADE;",
            ),

            # ==========================================
            # 3. Trigger Attachment: trigger_manage_property_status
            # ==========================================
            # Drop the trigger first to ensure idempotency (can be run multiple times safely)
            migrations.RunSQL(
                sql="DROP TRIGGER IF EXISTS trigger_manage_property_status ON lease_agreement;",
                reverse_sql=migrations.RunSQL.noop,
            ),
            migrations.RunSQL(
                sql="""
                    CREATE TRIGGER trigger_manage_property_status
                    -- UPDATED: Matched 'lease_agreement' table name
                    AFTER INSERT OR DELETE ON lease_agreement
                    FOR EACH ROW EXECUTE FUNCTION auto_update_property_status();
                """,
                reverse_sql="DROP TRIGGER IF EXISTS trigger_manage_property_status ON lease_agreement;",
            ),
        ]