# Generated by Django 6.0.3 on 2026-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20260510_1836'),
    ]

    operations = [
            migrations.RunSQL(
                sql="""
                    CREATE OR REPLACE PROCEDURE assign_staff_to_client(
                        p_client_no VARCHAR,
                        p_staff_no VARCHAR
                    )
                    LANGUAGE plpgsql AS $$
                    DECLARE
                        v_client_branch VARCHAR;
                        v_staff_branch VARCHAR;
                    BEGIN
                        -- ==========================================================
                        -- 1. CONCURRENCY: Lock the Client Row (Write Lock)
                        -- 'FOR UPDATE' exclusively locks the client row. If someone else
                        -- is trying to update this client at the same time, they wait here.
                        -- ==========================================================
                        SELECT registering_branch_no INTO v_client_branch
                        -- UPDATED: Matched 'client' table name
                        FROM client
                        WHERE client_no = p_client_no
                        FOR UPDATE;

                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Assignment failed: Client % does not exist.', p_client_no;
                        END IF;

                        -- ==========================================================
                        -- 2. CONCURRENCY: Lock the Staff Row (Read Lock)
                        -- 'FOR SHARE' prevents the staff member's record from being 
                        -- deleted or moved to a different branch while we check them.
                        -- ==========================================================
                        SELECT branch_no INTO v_staff_branch
                        -- UPDATED: Matched 'staff' table name
                        FROM staff
                        WHERE staff_no = p_staff_no
                        FOR SHARE;

                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Assignment failed: Staff member % does not exist.', p_staff_no;
                        END IF;

                        -- 3. Business Logic Check: Do they belong to the same branch?
                        IF v_client_branch IS DISTINCT FROM v_staff_branch THEN
                            RAISE EXCEPTION 'Assignment failed: Cross-branch assignment. Client is at branch %, but Staff is at branch %.', 
                                            COALESCE(v_client_branch, 'NONE'), COALESCE(v_staff_branch, 'NONE');
                        END IF;

                        -- 4. Perform the assignment
                        -- UPDATED: Matched 'client' table name
                        UPDATE client
                        SET registering_staff_no = p_staff_no
                        WHERE client_no = p_client_no;

                        -- ==========================================================
                        -- 5. TRANSACTION: Explicit Commit
                        -- Safely commit the changes and release all row locks immediately.
                        -- ==========================================================
                        COMMIT;

                        RAISE NOTICE 'Successfully assigned Staff % to Client %.', p_staff_no, p_client_no;
                    END;
                    $$;
                """,
                reverse_sql="DROP PROCEDURE IF EXISTS assign_staff_to_client(VARCHAR, VARCHAR);"
            ),
        ]