# Generated by Django 6.0.3 on 2026-05-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_fix_lease_trigger_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION validate_renter_preferences()
                RETURNS TRIGGER AS $$
                DECLARE
                    v_client_role VARCHAR;
                BEGIN
                    -- 1. Ensure the associated client actually has the role of 'Renter'
                    SELECT role INTO v_client_role 
                    FROM client 
                    WHERE client_no = NEW.client_no_id;

                    IF v_client_role != 'Renter' THEN
                        RAISE EXCEPTION 'Requirements can only be added for clients with role = Renter. Client % is a(n) %.', NEW.client_no_id, v_client_role;
                    END IF;

                    -- 2. Validate maximum monthly rent
                    IF NEW.max_monthly_rent IS NOT NULL AND NEW.max_monthly_rent <= 0 THEN
                        RAISE EXCEPTION 'Maximum monthly rent must be greater than zero.';
                    END IF;
                        
                    -- 3. Validate preferred property type
                    IF NEW.pref_property_type IS NOT NULL AND NEW.pref_property_type NOT IN ('Flat', 'House') THEN
                        RAISE EXCEPTION 'Invalid preferred property type. Must be Flat or House.';
                    END IF;
                    
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
