# Generated by Django 6.0.3 on 2026-05-25 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_auto_20260523_1157'),
        ('users', '0019_fix_renter_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffixes', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telephone_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nin', models.CharField(max_length=50, verbose_name='National Insurance Number')),
                ('position', models.CharField(choices=[('Staff', 'Standard Staff'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Secretary', 'Secretarial Staff')], help_text='Role being applied for.', max_length=50)),
                ('preferred_start_date', models.DateField()),
                ('typing_speed', models.IntegerField(blank=True, help_text='Secretarial applicants only (Words Per Minute).', null=True, validators=[django.core.validators.MinValueValidator(10, message='Typing speed must be at least 10 WPM.'), django.core.validators.MaxValueValidator(250, message='Typing speed cannot exceed 250 WPM.')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('nok_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_suffixes', models.CharField(blank=True, max_length=10, null=True)),
                ('nok_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_address', models.CharField(blank=True, max_length=255, null=True)),
                ('nok_telephone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_applications', to='users.staff')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='branches.branch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='users.staff')),
            ],
            options={
                'db_table': 'hiring_application',
            },
        ),
    ]
