# Generated by Django 6.0.3 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_hiringapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiringapplication",
            name="salary",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
