# Generated by Django 6.0.3 on 2026-05-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_hiringapplication_salary'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION get_staff_performance_report(p_branch_no VARCHAR DEFAULT NULL)
            RETURNS TABLE (
                staff_no VARCHAR,
                full_name TEXT,
                staff_position VARCHAR,
                properties_managed BIGINT,
                leases_arranged BIGINT,
                payments_processed BIGINT,
                clients_registered BIGINT
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    s.staff_no::VARCHAR,
                    (s.first_name || ' ' || s.last_name)::TEXT as full_name,
                    s.position::VARCHAR as staff_position,
                    COUNT(DISTINCT p.property_no) as properties_managed,
                    COUNT(DISTINCT l.lease_no) as leases_arranged,
                    COUNT(DISTINCT pay.payment_no) as payments_processed,
                    COUNT(DISTINCT c.client_no) as clients_registered
                FROM staff s
                LEFT JOIN property p ON s.staff_no = p.staff_no_id
                LEFT JOIN lease_agreement l ON s.staff_no = l.staff_no_id
                LEFT JOIN payment pay ON s.staff_no = pay.processed_by_staff_no
                LEFT JOIN client c ON s.staff_no = c.registering_staff_no
                WHERE (p_branch_no IS NULL OR s.branch_id = p_branch_no)
                GROUP BY s.staff_no, s.first_name, s.last_name, s.position
                ORDER BY properties_managed DESC, leases_arranged DESC;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS get_staff_performance_report(VARCHAR);"
        )
    ]
