# Generated by Django 6.0.3 on 2026-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_no', models.CharField(blank=True, editable=False, help_text='Auto-generated 3-character identifier (e.g., B01)', max_length=3, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('telephone_no', models.CharField(max_length=50)),
                ('fax_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
