# Generated by Django 6.0.3 on 2026-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20260404_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='area',
            field=models.CharField(blank=True, choices=[('Carmen', 'Carmen'), ('Lapasan', 'Lapasan'), ('Macasandig', 'Macasandig'), ('Poblacion', 'Poblacion'), ('Lumbia', 'Lumbia')], help_text='Select the Barangay', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_no',
            field=models.CharField(blank=True, editable=False, max_length=3, primary_key=True, serialize=False),
        ),
    ]
