# Generated by Django 6.0.3 on 2026-04-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_area_alter_branch_branch_no'),
        ('users', '0002_alter_nextofkin_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(blank=True, help_text='The specific staff member managing this branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to='users.staff'),
        ),
    ]
