# Generated by Django 6.0.3 on 2026-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_no',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
