# Generated by Django 6.0.3 on 2026-05-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branch_branch_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='manager',
            new_name='manager_no',
        ),
    ]
