# Generated by Django 6.0.4 on 2026-05-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_rename_manager_branch_manager_no'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Drop the function first to avoid "cannot change name of input parameter" errors
DROP FUNCTION IF EXISTS get_branch_client_count(VARCHAR);

CREATE OR REPLACE FUNCTION get_branch_client_count(p_branch_no VARCHAR)
RETURNS TABLE (
    total_owners INTEGER,
    total_renters INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        -- Count unique owners linked to this branch via the properties table
        (SELECT COUNT(DISTINCT owner_id)::INTEGER 
         FROM properties_property 
         WHERE branch_id = p_branch_no) AS total_owners,
         
        -- Count renters (Assuming 'Renter' logic exists in your business rules)
        -- Note: If renters aren't linked to branches in these images, 
        -- this will return 0 or needs a specific link table.
        (SELECT COUNT(*)::INTEGER 
         FROM users_client 
         WHERE role = 'Renter') AS total_renters; 
END;
$$ LANGUAGE plpgsql;
""")
    ]
