# Generated by Django 6.0.3 on 2026-05-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_auto_20260506_0958'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
