# Generated by Django 6.0.3 on 2026-05-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_branch_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION fn_branch_guard_and_validate()
            RETURNS TRIGGER
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_manager_position TEXT;
            BEGIN
                -- CLEANING 
                NEW.street   := btrim(NEW.street);
                NEW.city     := initcap(btrim(NEW.city));
                NEW.postcode := upper(btrim(NEW.postcode));
                NEW.area     := CASE
                                    WHEN NEW.area IS NULL OR btrim(NEW.area) = '' THEN NULL
                                    ELSE initcap(btrim(NEW.area))
                                END;

                -- STEP 2: VALIDATION (The "Logic" part)
                -- Check required fields AFTER they have been trimmed
                IF NULLIF(NEW.street, '') IS NULL THEN RAISE EXCEPTION 'Street is required'; END IF;
                IF NULLIF(NEW.city, '') IS NULL THEN RAISE EXCEPTION 'City is required'; END IF;

                -- Geographic Check
                IF NEW.area IS NOT NULL AND NEW.area NOT IN ('Carmen', 'Lapasan', 'Macasandig', 'Poblacion', 'Lumbia') THEN
                    RAISE EXCEPTION 'Invalid area: %', NEW.area;
                END IF;

                -- Regex Patterns
                IF NEW.postcode !~ '^[A-Za-z0-9 -]{3,20}$' THEN RAISE EXCEPTION 'Invalid postcode format'; END IF;
                IF NEW.telephone_no !~ '^\+?[0-9()[:space:]-]{7,50}$' THEN RAISE EXCEPTION 'Invalid telephone format'; END IF;

                -- Manager Check (Using your actual column: manager_no_id)
                IF NEW.manager_no_id IS NOT NULL THEN
                    SELECT position INTO v_manager_position FROM staff WHERE staff_no = NEW.manager_no_id;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Manager % does not exist', NEW.manager_no_id;
                    ELSIF v_manager_position <> 'Manager' THEN
                        RAISE EXCEPTION 'Staff % is not a Manager', NEW.manager_no_id;
                    END IF;
                END IF;

                -- Step 3: SUCCESS
                RETURN NEW;
            END;
            $$;

            -- Apply to the table
            DROP TRIGGER IF EXISTS tr_branch_details_guard ON branch;
            CREATE TRIGGER tr_branch_details_guard
            BEFORE INSERT OR UPDATE ON branch
            FOR EACH ROW
            EXECUTE FUNCTION fn_branch_guard_and_validate();
            """)
    ]
