# Generated by Django 6.0.3 on 2026-05-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_auto_20260508_1111'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION fn_validate_staff_details()
            RETURNS TRIGGER
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_min_salary NUMERIC;
            BEGIN
                -- 1. Validate Position and Get Salary Floor (Replacing IF/ELSE with a lookup)
                SELECT min_sal INTO v_min_salary
                FROM (VALUES 
                    ('Manager', 30000), 
                    ('Supervisor', 22000), 
                    ('Secretary', 15000), 
                    ('Staff', 12000)
                ) AS roles(pos, min_sal)
                WHERE pos = NEW.position;

                IF v_min_salary IS NULL THEN
                    RAISE EXCEPTION 'Invalid position: %. Must be Manager, Supervisor, Secretary, or Staff.', NEW.position;
                END IF;

                -- 2. Validate Salary against the floor
                IF NEW.salary IS NULL OR NEW.salary < v_min_salary THEN
                    RAISE EXCEPTION '% salary must be >= % (Current: %)', NEW.position, v_min_salary, COALESCE(NEW.salary, 0);
                END IF;

                -- 3. Specific Role Requirements
                -- Secretary Typing Speed Check
                IF NEW.position = 'Secretary' AND (NEW.typing_speed IS NULL OR NEW.typing_speed NOT BETWEEN 10 AND 250) THEN
                    RAISE EXCEPTION 'Secretaries require a typing speed between 10 and 250 WPM';
                END IF;

                -- Manager Start Date Check
                IF NEW.position = 'Manager' AND NEW.manager_start_date IS NULL THEN
                    RAISE EXCEPTION 'Managers must have a manager_start_date';
                END IF;

                RETURN NEW;
            END;
            $$;
            
            -- 1. Drop the trigger if it already exists to avoid errors
            DROP TRIGGER IF EXISTS trg_validate_staff_details ON staff;

            -- 2. Create the trigger
            CREATE TRIGGER trg_validate_staff_details
            BEFORE INSERT OR UPDATE ON staff
            FOR EACH ROW
            EXECUTE FUNCTION fn_validate_staff_details();
            """
        )
    ]
