# Generated by Django 6.0.3 on 2026-05-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_auto_20260508_1147'),
    ]

    operations = [
    ]
