# Generated by Django 6.0.3 on 2026-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_auto_20260508_1507'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE PROCEDURE sp_assign_staff_to_branch(
                    p_staff_no VARCHAR,
                    p_branch_id VARCHAR,
                    p_position TEXT,
                    p_supervisor_id VARCHAR DEFAULT NULL,
                    p_typing_speed INTEGER DEFAULT NULL,
                    p_manager_start_date DATE DEFAULT NULL,
                    p_bonus_payment NUMERIC DEFAULT NULL,
                    p_car_allowance NUMERIC DEFAULT NULL
                )
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    v_old_branch VARCHAR;
                    v_old_position TEXT;
                BEGIN
                    -- =========================================================
                    -- 1. CONCURRENCY CONTROL (The Locks)
                    -- =========================================================
                    
                    -- Lock 1: The Target Employee
                    SELECT branch_id, position
                    INTO v_old_branch, v_old_position
                    FROM staff
                    WHERE staff_no = p_staff_no
                    FOR UPDATE;

                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Staff % not found', p_staff_no;
                    END IF;

                    -- Lock 2: The Destination Branch
                    IF p_branch_id IS NOT NULL THEN
                        PERFORM 1 FROM branch WHERE branch_no = p_branch_id FOR UPDATE;
                        IF NOT FOUND THEN 
                            RAISE EXCEPTION 'Branch % not found', p_branch_id; 
                        END IF;
                    END IF;

                    -- Lock 3: The Target Supervisor
                    IF p_supervisor_id IS NOT NULL THEN
                        PERFORM 1 FROM staff WHERE staff_no = p_supervisor_id FOR UPDATE;
                        IF NOT FOUND THEN 
                            RAISE EXCEPTION 'Supervisor % not found', p_supervisor_id; 
                        END IF;
                    END IF;

                    -- =========================================================
                    -- 2. BUSINESS LOGIC (The Updates)
                    -- =========================================================
                    
                    -- Update the staff member. 
                    -- NOTE: Your BEFORE UPDATE triggers will automatically fire right here!
                    UPDATE staff
                    SET branch_id          = p_branch_id,
                        position           = p_position,
                        supervisor_id      = p_supervisor_id,
                        typing_speed       = CASE WHEN p_position = 'Secretary' THEN p_typing_speed ELSE NULL END,
                        manager_start_date = CASE WHEN p_position = 'Manager' THEN p_manager_start_date ELSE NULL END,
                        bonus_payment      = CASE WHEN p_position = 'Manager' THEN p_bonus_payment ELSE NULL END,
                        car_allowance      = CASE WHEN p_position = 'Manager' THEN p_car_allowance ELSE NULL END
                    WHERE staff_no = p_staff_no;

                    -- Sync Step A: Clean up the old branch if they were a Manager and are leaving
                    IF v_old_position = 'Manager' AND v_old_branch IS NOT NULL 
                    AND (p_position <> 'Manager' OR p_branch_id IS DISTINCT FROM v_old_branch) THEN
                        UPDATE branch
                        SET manager_no_id = NULL
                        WHERE branch_no = v_old_branch AND manager_no_id = p_staff_no;
                    END IF;

                    -- Sync Step B: Set them as the Manager of the new branch
                    IF p_position = 'Manager' AND p_branch_id IS NOT NULL THEN
                        UPDATE branch
                        SET manager_no_id = p_staff_no
                        WHERE branch_no = p_branch_id;
                    END IF;

                    -- =========================================================
                    -- 3. TRANSACTION CONTROL (The Save)
                    -- =========================================================
                    COMMIT; -- Permanently saves the changes and releases all locks.

                EXCEPTION
                    -- =========================================================
                    -- 4. ERROR HANDLING (The Undo)
                    -- =========================================================
                    WHEN OTHERS THEN
                        ROLLBACK; -- Completely reverses any partial updates made above.
                        RAISE;    -- Spits the error back out to Django.
                END;
                $$;
            """
        )
    ]
