# Generated by Django 6.0.3 on 2026-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_auto_20260508_1507'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            
            """
        )
    ]
