# Generated by Django 6.0.3 on 2026-05-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_auto_20260508_1731'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE PROCEDURE sp_update_staff_profile(
                    p_staff_no VARCHAR,
                    p_position TEXT,
                    p_salary NUMERIC,
                    p_branch_id VARCHAR DEFAULT NULL,
                    p_supervisor_id VARCHAR DEFAULT NULL,
                    p_typing_speed INTEGER DEFAULT NULL,
                    p_manager_start_date DATE DEFAULT NULL,
                    p_bonus_payment NUMERIC DEFAULT NULL,
                    p_car_allowance NUMERIC DEFAULT NULL
                )
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    v_old_branch VARCHAR;
                    v_old_position TEXT;
                BEGIN
                    -- =========================================================
                    -- 1. CONCURRENCY CONTROL (The Locks)
                    -- =========================================================
                    
                    -- Lock 1: Target Employee
                    SELECT branch_id, position
                    INTO v_old_branch, v_old_position
                    FROM staff
                    WHERE staff_no = p_staff_no
                    FOR UPDATE;

                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Staff % not found', p_staff_no;
                    END IF;

                    -- Lock 2: Target Branch
                    IF p_branch_id IS NOT NULL THEN
                        PERFORM 1 FROM branch WHERE branch_no = p_branch_id FOR UPDATE;
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Branch % not found', p_branch_id;
                        END IF;
                    END IF;

                    -- Lock 3: Target Supervisor
                    IF p_supervisor_id IS NOT NULL THEN
                        PERFORM 1 FROM staff WHERE staff_no = p_supervisor_id FOR UPDATE;
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Supervisor % not found', p_supervisor_id;
                        END IF;
                        
                        -- Prevent absolute loop before triggers even fire
                        IF p_supervisor_id = p_staff_no THEN
                            RAISE EXCEPTION 'Staff cannot supervise themselves';
                        END IF;
                    END IF;

                    -- =========================================================
                    -- 2. BUSINESS LOGIC (The Updates)
                    -- =========================================================
                    
                    -- Update the staff profile.
                    -- (Your database triggers will immediately fire here to validate the salary and role!)
                    UPDATE staff
                    SET position           = p_position,
                        salary             = p_salary,
                        branch_id          = p_branch_id,
                        supervisor_id      = p_supervisor_id,
                        typing_speed       = CASE WHEN p_position = 'Secretary' THEN p_typing_speed ELSE NULL END,
                        manager_start_date = CASE WHEN p_position = 'Manager' THEN p_manager_start_date ELSE NULL END,
                        bonus_payment      = CASE WHEN p_position = 'Manager' THEN p_bonus_payment ELSE NULL END,
                        car_allowance      = CASE WHEN p_position = 'Manager' THEN p_car_allowance ELSE NULL END
                    WHERE staff_no = p_staff_no;

                    -- Sync Step A: Clean up old branch manager assignment if they are demoted or moved
                    IF v_old_position = 'Manager' AND v_old_branch IS NOT NULL 
                    AND (p_position <> 'Manager' OR p_branch_id IS DISTINCT FROM v_old_branch) THEN
                        UPDATE branch
                        SET manager_no_id = NULL
                        WHERE branch_no = v_old_branch AND manager_no_id = p_staff_no;
                    END IF;

                    -- Sync Step B: Set them as the Manager of the new branch (if applicable)
                    IF p_position = 'Manager' AND p_branch_id IS NOT NULL THEN
                        UPDATE branch
                        SET manager_no_id = p_staff_no
                        WHERE branch_no = p_branch_id;
                    END IF;

                    -- =========================================================
                    -- 3. TRANSACTION CONTROL
                    -- =========================================================
                    COMMIT; -- Save everything if no errors occurred

                EXCEPTION
                    -- =========================================================
                    -- 4. ERROR HANDLING
                    -- =========================================================
                    WHEN OTHERS THEN
                        ROLLBACK; -- Undo everything on failure
                        RAISE;
                END;
                $$;
            """
        )
    ]
