# Generated by Django 6.0.3 on 2026-05-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_auto_20260508_1752'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE PROCEDURE sp_save_branch(
                INOUT p_branch_no VARCHAR,
                p_street TEXT,
                p_area TEXT,
                p_city TEXT,
                p_postcode TEXT,
                p_telephone_no TEXT,
                p_fax_no TEXT DEFAULT NULL,
                p_manager_no VARCHAR DEFAULT NULL
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                -- =========================================================
                -- 1. CONCURRENCY CONTROL (The Locks)
                -- =========================================================

                -- Lock 1: Target Branch (Only if we are updating an existing branch)
                IF p_branch_no IS NOT NULL AND btrim(p_branch_no) <> '' THEN
                    PERFORM 1 FROM branch WHERE branch_no = p_branch_no FOR UPDATE;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Branch % not found', p_branch_no;
                    END IF;
                END IF;

                -- Lock 2: Target Manager & Exclusivity Check
                IF p_manager_no IS NOT NULL THEN
                    PERFORM 1 FROM staff WHERE staff_no = p_manager_no FOR UPDATE;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Manager % not found', p_manager_no;
                    END IF;

                    -- Prevent a manager from managing multiple branches simultaneously
                    IF EXISTS (
                        SELECT 1 FROM branch 
                        WHERE manager_no_id = p_manager_no 
                        AND branch_no <> COALESCE(p_branch_no, '')
                    ) THEN
                        RAISE EXCEPTION 'Manager % is already assigned to another branch', p_manager_no;
                    END IF;
                END IF;

                -- =========================================================
                -- 2. BUSINESS LOGIC (The Upsert)
                -- =========================================================
                -- (Your Database Triggers will fire during these statements to clean & validate the text!)

                IF p_branch_no IS NULL OR btrim(p_branch_no) = '' THEN
                    -- CREATE: Insert a brand new branch
                    INSERT INTO branch (
                        street, area, city, postcode, telephone_no, fax_no, manager_no_id
                    )
                    VALUES (
                        p_street, p_area, p_city, p_postcode, p_telephone_no, p_fax_no, p_manager_no
                    )
                    RETURNING branch_no INTO p_branch_no; -- Captures the auto-generated ID
                ELSE
                    -- UPDATE: Modify an existing branch
                    UPDATE branch
                    SET street        = p_street,
                        area          = p_area,
                        city          = p_city,
                        postcode      = p_postcode,
                        telephone_no  = p_telephone_no,
                        fax_no        = p_fax_no,
                        manager_no_id = p_manager_no
                    WHERE branch_no = p_branch_no;
                END IF;

                -- Sync Step: Ensure the assigned manager's staff record points to this branch
                IF p_manager_no IS NOT NULL THEN
                    UPDATE staff
                    SET branch_id = p_branch_no
                    WHERE staff_no = p_manager_no;
                END IF;

                -- =========================================================
                -- 3. TRANSACTION CONTROL
                -- =========================================================
                COMMIT; -- Permanently save all changes

            EXCEPTION
                -- =========================================================
                -- 4. ERROR HANDLING
                -- =========================================================
                WHEN OTHERS THEN
                    ROLLBACK; -- Undo everything if any step fails
                    RAISE;
            END;
            $$;
            """
        )
    ]
