# Generated by Django 6.0.3 on 2026-05-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_fix_branch_trigger_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION generate_branch_no()
RETURNS VARCHAR AS $$
DECLARE
    last_branch_no VARCHAR;
    new_seq INT;
BEGIN
    -- SELECT FROM 'branch' INSTEAD OF 'branches_branch'
    SELECT branch_no INTO last_branch_no
    FROM branch
    ORDER BY branch_no DESC
    LIMIT 1;

    IF last_branch_no IS NOT NULL AND last_branch_no ~ '^B[0-9]+$' THEN
        new_seq := CAST(SUBSTRING(last_branch_no FROM 2) AS INT) + 1;
    ELSE
        new_seq := 1;
    END IF;

    -- Concatenate 'B' directly with the text version of the number (no padding)
    RETURN 'B' || new_seq::TEXT;
END;
$$ LANGUAGE plpgsql;
            """)
    ]
